day1/BOJ_1018_체스판다시칠하기/BOJ_1018_체스판다시칠하기_김선후.java
=> [1일차] 김선후_BOJ_1018_체스판다시칠하기

day2/BOJ_2116_주사위쌓기/BOJ_2116_주사위쌓기_신현국.java, day2/BOJ_2304_창고다각형/BOJ_2304_창고다각형_신현국.java, day2/BOJ_2309_일곱난쟁이/BOJ_2309_일곱난쟁이_신현국.java
=> [2일차] 신현국_BOJ_월말평가대비_1

day2/BOJ_2116_주사위쌓기/BOJ_2116_주사위쌓기_김선후.java, day2/BOJ_2304_창고다각형/BOJ_2304_창고다각형_김선후.java, day2/BOJ_2309_일곱난쟁이/BOJ_2309_일곱난쟁이_김선후.java
1번 문제 주사위 쌓기
1. 주사위배열 저장순서 A-B-C-D-E-F 
2. 주사위 인덱스 0 1 2 3 4 5
3.  마주보는 한쌍 A-F, B-D, C-E
4.  한쌍의 인덱스중 하나만 탐색하도록 하고 인덱스가 위로 갈경우와 아래로 갈경우를 상정하여 쌓는다.
5.  예를 들어 0인덱스로 들어온 주사위가 이미 쌓아졌으면 5인덱스는 한쌍이므로 쌓지않도록 한다. 
6. 0이 위인경우와 아래인경우 두상황을 고려해본다.
2번 문제 창고다각형
1. 맨처음 시작 기둥과 그와 비교해서 현재까지 가장 높은기둥 그리고 마지막 기둥의 정보만 알수 있으면 된다.
2.  가장 처음 시작 기둥을 기준으로 높이비교를 하여 그다음으로 높은 기둥을 찾고 시작기둥과의 x값의 차*시작기둥높이까지를 저장해둔다.
3.  그다음으로 높은기둥을 이제 새로운 시작기둥으로 놓고 가장 높은 기둥이 나올떄까지 반복한다 .
4. 더이상 새로운 높은 기둥이 나오지 않으면 그 기둥이 모든 기둥중 제일 높은 기둥이므로 그다음부터는 마지막 기둥에서 부터 반복한다.
5. 마지막으로 제일 긴 기둥을 더해준다.
3번 문제 일곱 난쟁이
1. 조합 문제 9난쟁이중 7난쟁이를 뽑는데 그 일곱의 몸무게합이 100인 경우를 찾으면 끝난다.
2. 다른 방법으로는 처음부터 모든 키합을 구하고 2명의 난쟁이의 키를 뺀값이 100인 경우를 구할 수도 있다.
=> [2일차] 김선후_BOJ_월말평가대비_1

day2/BOJ_2116_주사위쌓기/BOJ_2116_주사위쌓기_박기윤.java, day2/BOJ_2304_창고다각형/BOJ_2304_창고다각형_박기윤.java, day2/BOJ_2309_일곱난쟁이/BOJ_2309_일곱난쟁이_박기윤.java
- BOJ_2309_일곱난쟁이
전형적인 `조합` 문제라고 생각하고 접근
- 9C7로 나올 수 있는 조합 중, 키의 합이 100이면 selectedHeight 배열에 넣어 오름차순 정렬 후 결과 출력
<br>
- BOJ_2304_창고다각형
- 기둥의 위치와 높이 정보를 갖는 2차원 배열 생성, 이 때 입력받으며 기둥의 최대 높이와 그 기둥의 위치를 미리 저장해둔다.
- Comparator를 이용하여 위치를 기준으로  2차원 배열 오름차순 정렬
- 1에서 구한 최대 높이 기둥 기준 왼쪽 탐색하며 면적 더하기
- 최대 높이 기둥 기준 오른쪽 탐색하며 면적 더하기
<br>
- BOJ_2116_주사위쌓기
- 주사위를 쌓는 **stack** 함수 작성. <br>
1-1. 옆면 숫자를 고려하지 않고 주사위를 쌓을 때 나올 수 있는 경우의 수는 총 6가지이다. → 1번 주사위(맨 아래 주사위)의 윗면이 A~F인 경우
1-2. 전개도를 보면 A,F /  C,E / D,B가 서로 마주봄을 알 수 있다. 따라서 윗면 인덱스를 아랫면 인덱스도 알 수 있다. 예시로 윗면 인덱스가 0, 즉 A면이면 아랫면 인덱스는 5, 즉 F면이다.
따라서 stack 함수는 `i번째 주사위의 윗면 인덱스`와 `몇 개를 쌓았는지를 의미하는 count 변수`를 매개변수로 갖는 재귀함수로 작성할 수 있다.
1-3. 인덱스를 알면 주사위에 적힌 숫자에 접근할 수 있기 때문에, i번째 주사위의 윗면 숫자와 i+1번째 주사위의 아랫면 숫자가 같도록 주사위를 계속 쌓고, 이 단계마다 옆면 숫자들을 배열에 저장한다.
1-4. count가 주사위 개수와 동일해지면 …
=> [2일차] 박기윤_BOJ_월말평가대비_1

day2/BOJ_2116_주사위쌓기/BOJ_2116_주사위쌓기.md, day2/BOJ_2304_창고다각형/BOJ_2304_창고다각형.md, day2/BOJ_2304_창고다각형/BOJ_2304_창고다각형_신영제.java, day2/BOJ_2309_일곱난쟁이/BOJ_2309_일곱난쟁이.md, day2/BOJ_2309_일곱난쟁이/BOJ_2309_일곱난쟁이_신영제.java
"주사위 쌓기" 
접근 방법 
: 최대값, 최소값 찾기 -> 정렬 -> 세우기 -> 옆면 비교 하며 최대값 // 문제이해 X 
"난쟁이" 
접근방법
: 삭제 할 수 있어야 하니깐 리스트로 접근.. ㅜㅜ 실패
=> [2일차]_신영제_BOJ_월말평가대비_1

day2/BOJ_2116_주사위쌓기/BOJ_2116_주사위쌓기_어정윤.java, day2/BOJ_2304_창고다각형/BOJ_2304_창고다각형_어정윤.java, day2/BOJ_2309_일곱난쟁이/BOJ_2309_일곱난쟁이_어정윤.java
=> [2일차] 어정윤_BOJ_월말평가대비_1

day2/BOJ_2116_주사위쌓기/BOJ_2116_주사위쌓기_어정윤.java, day3/BOJ_14696_딱지놀이/BOJ_14696_딱지놀이_어정윤.java, day3/BOJ_2477_참외밭/BOJ_2477_참외밭_어정윤.java, day3/BOJ_2491_수열/BOJ_2491_수열_어정윤.java, day3/BOJ_2669_직사각형네개의합집합면적구하기/BOJ_2669_직사각형네개의합집합면적구하기_어정윤.java
=> [3일차] 어정윤_BOJ_월말평가대비_2

day3/BOJ_14696_딱지놀이/BOJ_14696_딱지놀이_신현국.java, day3/BOJ_2477_참외밭/BOJ_2477_참외밭_신현국.java, day3/BOJ_2491_수열/BOJ_2491_수열_신현국.java, day3/BOJ_2669_직사각형네개의합집합면적구하기/BOJ_2669_직사각형네개의합집합면적구하기_신현국.java
=> [3일차] 신현국_BOJ_월말평가대비_2

day3/BOJ_14696_딱지놀이/BOJ_14696_신영제.java, day3/BOJ_2477_참외밭/BOJ_2477_신영제.java, day3/BOJ_2491_수열/BOJ_2491_신영제.java, day3/BOJ_2669_직사각형네개의합집합면적구하기/BOJ_2669_신영제.java
BOJ_2477_참외밭 
접근 방법 :  방향에 상관없이( (동쪽 서쪽중 가장 큰 값)  *  (남쪽 북쪽 가장 큰 값)) - ( (동쪽 서쪽중 가장 작은 값)  *  (남쪽 북쪽 가장 작은 값)) * 참외 갯수 를 구하는 방법으로 접근 했습니다. 
결과는 같게 나오는데 백준에서는 틀렸다고 하네요 ㅠㅠ 반례도 다맞았는데 한번 더 신중히 찾아 보겠습니다!
BOJ_2491_수열
연속적인 숫자이니깐 연속적이지 않은 숫자를 만나면 다시 초기화하면 되겠구나 생각했습니다. 
가장 처음으로 카운트를 추가하면서 하게 된다면 쉽게 될 거라 생각했지만 자신보다 작은 숫자를 만나면 다시 초기화해야 되는 부분이 있었습니다. 그래서 카운트의 개수를 저장하고 max 값을 비교하면 되겠구나 싶었습니다. 근데 또 하나의 문제가 계속 증가만 하는 게 아니라 계속 감소도 하는 반례도 있었습니다. 그래서 같은 for 문안에 두 개의 if 문을 돌려 해당하는 값에서 실행하게 하였습니다! 
BOJ_2669_직사각형....
색종이 면적 구하기를 생각해보았습니다! 
대신 다르게 생각한 부분은 1을 다시 덮어서 면적을 구해보는 방법으로 했습니다.
BOJ_14996_딱지놀이
조건이 4 - 3 - 2 - 1 순서로 우선순위가 메겨집니다. 즉 각 숫자마다 카운트 수로 초기화 시켜 값을 비교하는 문제라 생각됩니다. 어려웠던 부분은 무승부일 때 결과 도출이었는데, 4 ~ 2까지는 다음 숫자를 비교하고 1까지 숫자가 같다면 위 숫자들이 전체 다 같다는 전개가 있기 때문에 1일 때는 무승부를 나오게 하였습니다!!
=> [3일차] 신영제_BOJ_월말평가대비_2

day4/BOJ_13300_방배정/BOJ_13300_방배정_어정윤.java, day4/BOJ_1592_영식이와친구들/BOJ_1592_영식이와친구들_어정윤.java, day4/BOJ_2564_경비원/BOJ_2564_경비원_어정윤.java, day4/BOJ_2605_줄세우기/BOJ_2605_줄세우기_어정윤.java
=> [4일차] 어정윤_BOJ_월말평가대비_3

day4/BOJ_13300_방배정/BOJ_13300_방배정_신영제.java, day4/BOJ_1592_영식이와친구들/BOJ_1592_영식이와친구들_신영제.java, day4/BOJ_2564_경비원/BOJ_2564_경비원_신영제_못품.java, day4/BOJ_2605_줄세우기/BOJ_2605_줄세우기_신영제.java
< 경비원 > 
조건문과 규칙을 찾아 최소 거리를 구하면 접근을 할 수 있을거 같습니다. 
100% 제 게으름으로 인해 시간 안에 풀지 못하여 미제출 하게 되었습니다 ㅠㅠ 
<영식이와 친구들>
큐 리스트? 로 풀 수 있을거 같은데 떠오르지가 않아 배열형식 으로 범위를 벗어나면 나누기, 1아래면 +크기를 하여 쉽게 접근 할 수 있었습니다. 
<방배정>
규칙은 충분히 이해 했지만 방을 카운트 하는 방법을 찾지 못했어서 시간이 오래 걸렸습니다 
<줄세우기>
리스트의 방법이 익숙하지 않아 많이 찾아가며 삽입에 대해 배웠습니다!
=> [4일차] 신영제_BOJ_월말평가대비_3

day4/BOJ_13300_방배정/BOJ_13300_방배정_김선후.java, day4/BOJ_1592_영식이와친구들/BOJ_1592_영식이와친구들_김선후.java, day4/BOJ_2564_경비원/BOJ_2564_경비원_김선후.java, day4/BOJ_2605_줄세우기/BOJ_2605_줄세우기_김선후.java
1번 문제 줄 세우기
1. 학생 수 만큼 번호를 받아서 넣을 수 있는 학생리스트를 사용한다. 
2. 학생 수 만큼 입력받은 번호를 num이 0일 경우에는 리스트에 그대로 있게 한다.
3. 학생 인덱스(들어온 순서) - num(입력받은 숫자)가 리스트에서 위치한 인덱스 값이 된다.
2번 문제 영식이와 친구들
1.공을 받은 해당 인덱스의 값이 홀수일 시 시계방향 L만큼 공을 던지고 
2.만약 인덱스가 범위를 벗어나면 (인덱스+L)%N 
3.짝수일 시 반시계방향 L만큼 공을 던진다 
4.만약 인덱스가 범위를 벗어나면(인덱스-L)+N 
5.공을 던진 후 공을 받은 인덱스의 배열값을 증가시킨다.
3번 문제 방배정	
학년 1-6학년까지 있음.
여학생과 남학생으로 성별이 나뉨
학년 / 여학생 / 남학생
1
2
3
4
5
6
7*2 혹은 2*7 크기의 배열로 나타낼 수 있음.
학년은 1인덱스부터 사용
해당 학년의 성별에 따라서 인덱스의 배열값 증가
1. 1학년부터 6학년까지 탐색을 돌리며 3가지 경우로 방 수를 계산함.
2. 해당학년의 성별이 K수보다 작거나 같다면 +1
3. 해당학년의 성별이 %K==0이면 /K값만큼 방 수증가
4. 해당학년의 성별이 %K!=0이면 /K값만큼 방수를 증가시키고 한번 더 증가.
4번 문제 경비원
/* fail
* 블록을 가로지를 수 없기때문에 동근이와 상점의 거리공식은 언제나 3가지의 경우로 나눠진다.
*  동근이와 상점이 같은 열에 있을 경우 동근이의 x좌표와 상점의 x좌표사이의 거리를 구한다.
*  동근이와 상점이 같은 행에 있을 경우 동근이의 y좌표와 상점의 y좌표사이의 거리를 …
=> [4일차] 김선후_BOJ_월말평가대비_3

day4/BOJ_13300_방배정/BOJ_13300_방배정_신현국.java, day4/BOJ_1592_영식이와친구들/BOJ_1592_영식이와친구들_신현국.java, day4/BOJ_2564_경비원/BOJ_2564_경비원_신현국.java, day4/BOJ_2605_줄세우기/BOJ_2605_줄세우기_신현국.java
=> [4일차] 신현국_BOJ_월말평가대비_3

day4/BOJ_13300_방배정/BOJ_13300_방배정_박기윤.java, day4/BOJ_1592_영식이와친구들/BOJ_1592_영식이와친구들_박기윤.java, day4/BOJ_2564_경비원/BOJ_2564_경비원_박기윤.java, day4/BOJ_2605_줄세우기/BOJ_2605_줄세우기_박기윤.java
- 방배정
1. studentCnt라는 6X2 크기의 int Type 배열 생성 (행: 학년, 열: 성별)
2. 입력값을 받으며 해당 학생이 속하는 배열 값+1
3. 2번 과정을 통해 입력을 모두 처리한 후, 배열의 모든 요소를 돌며 K를 나눈 값을 올림하여 누적한다.
<br>
- 영식이와 친구들
1. 해당 자리에서 공을 받은 횟수를 저장할 getBall 1차원 배열 생성. 문제에서 자리는 1번부터 시작하므로 크기를 N+1로 주었다.
2. 공을 던지는 사람과 받는 사람을 저장할 from, to 변수 선언. 맨 처음 공을 받는 사람은 1번 자리에 앉은 사람이므로 to에는 1값을 준다.
3. 반복문 처리
　3-1. getBall[to]값 +1 후, 이 값이 M값과 같으면 break
　3-2. to를 from으로 변경(공을 받은 사람이 던지는 사람이 된다.)
　3-3. getBall[from] 값이 홀수이면 from+L의 자리에 있는 사람이 to가 된다. 이 값이 N보다 큰 경우에는 (from+L)%N이 to가 된다. / getBall[from] 값이 짝수이면 from-L의 자리에 있는 사람이 to가 된다. 이 값이 1보다 작으면 (from-L)+N이 to가 된다.
　3-4. from과 to가 모두 정해졌으므로 공을 던진다.(공 던진 횟수인 count+1)
<br>
- 경비원
1. 방향, x좌표, y좌표를 멤버 변수로 갖는 Location class 선언
2. Location 객체를 담는 storeLoc 객체 배열 생성 후 상점의 정보를 담는다. 경비원의 정보는 Location형 guard 객체에 담는다.
3. …
=> [4일차] 박기윤_BOJ_월말평가대비_3

day5/BOJ_2527_직사각형/BOJ_2527_직사각형_김선후_100오답.java, day5/BOJ_2559_수열/BOJ_2559_수열_김선후.java, day5/BOJ_2578_빙고/BOJ_2578_빙고_김선후.java, day5/BOJ_2628_종이자르기/BOJ_2628_종이자르기_김선후.java
1번 문제 직사각형
1.먼저 공통부분이 없는 부분을 기준으로 공통부분인 부분을 찾습니다.
첫 직사각형의 x2보다 두번째 직사각형의 x1값이 큰 경우
첫 직사각형의 x1이 두번째 직사각형의 x2값보다 큰 경우
첫 직사각형의 y2보다 두번째 직사각형의 y1값이 큰 경우
첫 직사각형의 y1이 두번째 직사각형의 y2값보다 큰 경우
2.그다음 각 면에 대해서 검사해서 점인지 선인지를 확인합니다.
결과 : 100%에서 틀립니다. ㅠㅠㅠ
2번 문제 수열
첫번째 실패 : 리스트를 두개 쓰면 시간초과가 나옵니다.
1.N개의 크기를 지닌 배열을 선언해서 N개의 온도를 담아줍니다.
2.연산결과의 수열의 개수는 N-K+1개입니다.
3.반복문에서 연산의 시작값을 인덱스의 초기값으로 두고 초기값+K-1의 인덱스까지 연산을 반복합니다.
4.결과값을 ansList에 넣고 오름차순 정렬을 해주며 최종값은 리스트의 마지막 인덱스입니다.
3번 문제 빙고
1.빙고판 배열을 만들어 둔다.
2.빙고판배열에 입력값으로 초기해둔다.
3.사회자가 부른 수를 0로 변경해주고 가로 세로 대각선을 돌면서 빙고판이 0인 경우 cnt을 체크한다.
4.cnt가 5가 나오면 선이 하나 그어지므로 그 순간 line을 증가시켜준다.
5.그와 동시에 line값을 체크해주며 line값이 3이상이면 빙고 처리를 해준다.
4번 문제 종이자르기
1.x좌표 리스트와 y좌표 리스트를 만든다.
2.0번 인덱스에 최소값을 넣어준다. 인덱스를 1번부터 사용할 예정.
3.리스트를 오름차순 정렬한다.
4.이중반복문을 돌면서 x*y의 모든 경우를 구한다.
5.그중 가장 최대값을 매순간 …
=>  [5일차] 김선후_BOJ_월말평가대비_4

day5/BOJ_2527_직사각형/BOJ_2527_직사각형_어정윤.java, day5/BOJ_2559_수열/BOJ_2559_수열_어정윤.java, day5/BOJ_2578_빙고/BOJ_2578_빙고_어정윤.java, day5/BOJ_2628_종이자르기/BOJ_2628_종이자르기_어정윤.java
=> [5일차] 어정윤_BOJ_월말평가대비_4

day5/BOJ_2527_직사각형/BOJ_2527_직사각형_신현국.java, day5/BOJ_2559_수열/BOJ_2559_수열_신현국.java, day5/BOJ_2578_빙고/BOJ_2578_빙고_신현국.java, day5/BOJ_2628_종이자르기/BOJ_2628_종이자르기_신현국.java
=> [5일차] 신현국_BOJ_월말평가대비_4

day5/BOJ_2527_직사각형/BOJ_2527_직사각형_신영제.java, day5/BOJ_2559_수열/BOJ_2559_수열_신영제.java, day5/BOJ_2578_빙고/BOJ_2578_빙고_신영제.java, day5/BOJ_2628_종이자르기/BOJ_2628_종이자르기_신영제.java
종이자르기
1) 가로 세로 리스트 생성
2) 리스트당 값 넣고 정렬.
3) 정렬한 값을 ( i+1) - ( i ) 해주면 자른 부분마다 넓이가 구해짐 가장 큰값을 넣는다.
4) 큰값들을 곱하면 넓이가 구해진다.
빙고
1) 내 점수 배열 만든다. + boolean배열을 만든다 ( true값으로 빙고로 만들기 위해)
2) 사회자 점수 배열 만든다.
3) 각 빙고 라인에 맞는 메서드를 만든다. 
4) 조건에 맞으면 그때 나온 사회자 숫자를 뽑는다. ( 실패 )  
수열
1) K만큼 더하기 위해 범위를 지정해준다.
2) 값마다 K만큼 더하기위해 반복을 한다.
3) sum에 더한 값을 넣고 가장 큰 값을 비교한다.
직사각형
1) 사각형에 해당하는 범위를 찾는다. 
2) 각 구역마다 범위에 해당하는 만큼 조건문을 만든다. ( 100%에서 계속 오류가나서 구글링 참조했습니다..!)
=> [5일차] 신영제_BOJ_월말평가대비_4

day6/BOJ_10157_자리배정/BOJ_10157_자리배정_김선후.java, day6/BOJ_10158_개미/BOJ_10158_개미_김선후.java, day6/BOJ_10163_색종이/BOJ_10163_색종이_김선후.java, day6/BOJ_2635_수이어가기/BOJ_2635_수이어가기_김선후.java
1번 문제 수 이어가기
1.문제에서 주어진 규칙을 살펴보았을 때 만들 수 있는 수들이 최대로 많아지려면
가장 먼저 규칙이 종료되는 조건 (기저조건)이 무엇인지부터 파악해야 합니다.
2.규칙이 종료되는 조건을 찾아보았을때 앞에있는 숫자 <= 뒤에있는 숫자 의 상황일때 바로 종료됩니다.
3.모든 숫자는 양의 정수로 와야하기때문에 무조건 1이상의 정수가 되어야만 해서 앞의 숫자와 같은 숫자도 제외합니다.
ex) 100 100 2개 종료
ex) 100 20 80 3개 종료
ex) 100 60 40 30 10 6 4 3 1 9개 종료
4.즉 규칙의 조건에 따라서 최대한 많은 수를 이어 넣기 위해서는 뒤에수 > 앞에수 / 2 의 조건이 성립되어야만 합니다.
2번 문제 자리배정
1.그림에는 열행을 기준으로 그림이 나타나 있는데 
일반적으로 자주 사용하는 행열로 사용하기 위해 입력을 반대로 받습니다.
보충시간때 bfs,dfs 예시를 보면서 dfs로 풀 수 있다는 걸 알았지만 처음에 기억이 안나서 기저조건이 없는 dfs식으로 완성이 되었습니다.
코드를 작성하고 나서 뒤늦게서야 기저조건만 추가해주면 dfs가 된다는걸 알았습니다.
2.방향별 시작좌표를 start 변수로 초기화해주고 한번의 반복이 끝날때마다 start를 증가시켜주면서 배열을 전부 채울때까지 반복합니다.
3번 문제 개미
문제를 읽고 그림을 보자마자 간단한 생각이 떠올랐습니다.
x축 경계를 만나면 nx(다음에 이동할 x좌표)에 반전(*-1)을주고
y축 경계를 만나면 ny(다음에 이동할 y좌표)에 반전(*-1)을주는식으로 풀어보면 되지 않을까 생각해보았습니다.
그러나 …
=> [6일차] 김선후_BOJ_월말평가대비_5

day6/BOJ_10157_자리배정/BOJ_10157_자리배정_어정윤.java, day6/BOJ_10158_개미/BOJ_10158_개미_어정윤.java, day6/BOJ_10163_색종이/BOJ_10163_색종이_어정윤.java, day6/BOJ_2635_수이어가기/BOJ_2635_수이어가기_어정윤.java
=> [6일차] 어정윤_BOJ_월말평가대비_5

day6/BOJ_10157_자리배정/BOJ_10157_자리배정_신현국.java, day6/BOJ_10158_개미/BOJ_10158_개미_신현국.java, day6/BOJ_10163_색종이/BOJ_10163_색종이_신현국.java, day6/BOJ_2635_수이어가기/BOJ_2635_수이어가기_신현국.java
=> [6일차] 신현국_BOJ_월말평가대비_5

day7/BOJ_10250_ACM호텔/BOJ_10250_ACM호텔_김선후.java, day7/BOJ_14503_로봇청소기/BOJ_14503_로봇청소기_김선후.java, day7/BOJ_2508_사탕박사고창영/BOJ_2508_사탕박사고창영_김선후.java
1번 문제 ACM 호텔
1.행열이 아닌 열행을 우선으로 방을 채워나간다.
2.손님의 번호를 열 H로 나눈몫에 1을 더하면 호수를 구할 수 있다.
3.층수는 손님의 번호를 열 H로 %연산해준다.
4.단 이때 N%H의 나머지가 0이면 H층 N?H호에 머문다.
2번 문제  로봇 청소기
1. 로봇이 있는 좌표를 청소한다.
2. 현재있는 위치에서 방향만 회전시킨 후 다음 좌표의 조건을 체크한다.
3. 다음 위치가 빈공간이거나 청소하지 않은 곳이면 1칸 이동후 1로 돌아간다.
4. 4방향 전부 탐색해도 3으로 넘어갈 수 없으면 현재 방향을 기준으로 후진한다.
5. 4의 조건을 만족할 수 없으면 로봇의 이동을 멈추고 청소된 공간을 체크한다.
3번 문제 사탕박사
1.2차원 배열에 입력된 문자들을 >o<의 경우엔 행열 탐색으로
2.
v
o
^
은 열행 탐색으로 각각 완전탐색을 돌리면서 해당 문자들이 나란히 있는 경우에만
3.정답 카운트를 증가시켜 준다.
=> [7일차] 김선후_BOJ_월말평가대비_6

day8/BOJ_14502_연구소/BOJ_14502_연구소_신현국.java, day8/BOJ_18352_특정거리의도시찾기/BOJ_18352_특정거리의도시찾기_신현국.java, day8/BOJ_2210_숫자판점프/BOJ_2210_숫자판점프_신현국.java, day8/BOJ_4963_섬의개수/BOJ_4963_섬의개수_신현국.java
=> [8일차] 신현국_BOJ_코테뿌셔_1

day8/BOJ_2210_숫자판점프/BOJ_2210_숫자판점프_신영제.java, day8/BOJ_4963_섬의개수/BOJ_4963_섬의개수_신영제.java
숫자판점프 
1) 전체를 탐색해야 하므로 첫번째로 DFS를 생각했습니다.
2) 6자리의 수 가 되면  멈춰야 하고 같은수가 반복될 수 있으니 정수형을 문자형으로 변경해 같은 값이 없다면 담는 형식으로 
진행 했습니다. 
섬의개수 
1) 전체를 탐색하며 1을 발견하면 진행되어야 하기 때문에 DFS방법을 생각했습니다.
2) 섬이 8방향 중 이어져 진다면 이동경로가 되기 때문에 8방향 탐색을 통해 1이 끊길때 카운트 1을 해보고자 했습니다.
특정거리의도시찾기 - 실패
1) 최단 거리를 찾기위해 BFS방법으로 진행되어야 된다 생각했습니다.
< 해보고자 했던거 >
1) 인접한 도시와 배열과 방문한 정보 배열, 최단거리에 해당하는 배열을 생성 
2) 인접한 도시를 탐색하며 방문하지 않은 곳이면 큐에 삽입하여 추가해가며 최단 거리를 구해보자. 
3) 이후 오른 차순 정렬을 하여 출력 - 값이 없다면 -1 출력
< 어려웠던 점 > 
BFS전 단계 배열 생성에 대하여 많은 고민을 많이 하였지만 구현에 성공하지 못했습니다.. ㅠㅠ 
연구소  - 미제출 (죄송합니다 ㅠㅠ)
=> [8일차] 신영제_BOJ_코테뿌셔_1

day8/BOJ_18352_특정거리의도시찾기/BOJ_18352_특정거리의도시찾기_어정윤.java, day8/BOJ_2210_숫자판점프/BOJ_2210_숫자판점프_어정윤.java, day8/BOJ_4963_섬의개수/BOJ_4963_섬의개수_어정윤.java
=> [8일차] 어정윤_BOJ_코테뿌셔_1

day9/BOJ_20055_컨베이어벨트위의로봇/BOJ_20055_컨베이어벨트위의로봇_김선후.java, day9/BOJ_3187_양치기꿍/BOJ_3187_양치기꿍_김선후.java, day9/BOJ_8983_사냥꾼/BOJ_8983_사냥꾼_김선후.java, day9/BOJ_8983_사냥꾼/BOJ_8983_사냥꾼_김선후_이진탐색개선.java
1번 문제 양치기 꿍
1.전체 늑대와 양의 수를 저장해둔다.
2.각 영역별로 늑대와 양의 수를 파악한다.
3.영역을 구분할 때 경계체크 울타리의 좌표를 만나면 경계를 벗어나는 조건을 넣어준다.
4.dfs/bfs 어느쪽도 상관없다. 늑대양은 대각선 이동불가(4방탐색)
5.대소비교를 통해서 전체값에서 조절한다.
2번 문제 사냥꾼
처음에는 예전에 실습시간에 풀어보았던 충전기 문제와 체스판 문제와 유사하여 브루트포스를 가장 먼저 떠올리고 모든 동물과 사대를 탐색하며 풀어본 결과 TLE가 떠서 실패.
O(M*N)의 해결방법이 아닌 다른 방법이 필요하다는 걸 알았습니다.
그러다가 결국 동물의 y좌표가 L을 넘어가는 경우는 처음부터 고려할 필요자체가 없다는 것을 깨닫고 동물을 기준으로 x좌표를 기준으로 반복문을 생각해봤습니다.
동물이 모든 사대 중 자신을 잡을 수 있는 사대 한개만 찾으면 되는 문제.
1.가장 확실하게 범위내에 포함되는 사대는 사대의 x좌표와 동물의 x좌표가 같은경우(단 y좌표가 L이하)
2.따라서 동물x좌표에서 가장 가까운 x좌표를 지니는 사대를 찾으면 된다.(단 사정거리 L을 만족하는 범위)
3.x좌표에 따라서 오름차순으로 위치가 정렬되어야 합니다.
4.동물의 x좌표 기준 왼쪽과 오른쪽을 확인해봅니다.
3번 문제 컨베이어 벨트 위의 로봇
문제 지문이 굉장히 불친절하고 난해해서 구현목표자체가 이해하기가 어려웠습니다.
특히 로봇이 대체 어느시점, 어느단계에서 벨트에 올라가는지, 벨트에서 내려와서 어찌 행동하는지를
이해하기까지 시간을 많이 사용한 문제였습니다.
로봇이 내려오고난 이후 …
=> [9일차] 김선후_BOJ_코테뿌셔_2

day8/BOJ_14502_연구소/BOJ_14502_연구소_어정윤.java, day9/BOJ_20055_컨베이어벨트위의로봇/BOJ_20055_컨베이어벨트위의로봇_어정윤.java, day9/BOJ_3187_양치기꿍/BOJ_3187_양치기꿍_어정윤.java, day9/BOJ_8983_사냥꾼/BOJ_8983_사냥꾼_어정윤.java
=> [9일차] 어정윤_BOJ_코테뿌셔_2

day9/BOJ_20055_컨베이어벨트위의로봇/BOJ_20055_컨베이어벨트위의로봇_신현국.java, day9/BOJ_3187_양치기꿍/BOJ_3187_양치기꿍_신현국.java, day9/BOJ_8983_사냥꾼/BOJ_8983_사냥꾼_신현국.java
=> [9일차] 신현국_BOJ_코테뿌셔_2

day10/BOJ_10775_공항/BOJ_10775_공항_김선후.java, day10/BOJ_1541_잃어버린괄호/BOJ_1541_잃어버린괄호_김선후.java
1번 문제 잃어버린 괄호
1. 문제에서 요구하는 조건은 계산 결과가 최소값이 나오는 것이다.
2. 1+2+3+4-5+6+7+8-9+10 의 임의의 식에서 최소 값이 나오려면 -를 구분자로 분리시켜야 한다.
3. (1+2+3+4)-(5+6+7+8)-(9+10) -로 구분된 식에서 첫번째 괄호영역은 결과값에 더해주고 나머지는 전부 빼준다.
주의 : java.util.regex.PatternSyntaxException : Dangling meta character 에러에 유의할 것
사실상 이스케이프 문제였던 것 같습니다.
2번 문제 공항
1.어떤 규칙으로 게이트에 비행기를 도킹해야지 가장 많은 비행기를 도킹시킬수 있는지 조건을 찾는다.
2.그림판으로 최선의 규칙을 찾아본 결과 g번 비행기는 g번 게이트에 도킹을 한다.
3.해당 게이트가 이미 도킹이 된 상태일 경우 g-1 게이트를 도킹한다.
4.g-1 게이트도 불가능 할 시 차례대로 g-2, g-3, g-4, ...0번게이트까지 확인한다.
5.g-1번 게이트를 선택해야하는 경우에 0번게이트가 선택되면 더 이상 빈게이트가 없으므로 종료된다.
ex) 4번비행기 4번게이트에 도킹
두번째 4번비행기 4<-이미 도킹됨. 4-1=3번게이트에 도킹
1번비행기 1번게이트에 도킹
두번째 1번비행기 1-0번게이트에 도킹(불가능) 종료.
최선이 아닌 차선의 선택을 하는 도중 게이트가 비었는지를 확인하는 과정에서 유니온파인드가 사용됨.
=> [10일차] 김선후_BOJ_코테뿌셔_3

day10/BOJ_10775_공항/BOJ_10775_공항_신현국.java, day10/BOJ_1541_잃어버린괄호/BOJ_1541_잃어버린괄호_신현국.java
=> [10일차] 신현국_BOJ_코테뿌셔_3

day10/BOJ_1541_잃어버린괄호/BOJ_1541_잃어버린괄호_어정윤.java
=> [10일차] 어정윤_BOJ_코테뿌셔_3

day10/BOJ_1541_잃어버린괄호/BOJ_1541_잃어버린괄호_신영제.java
잃어버린 괄호
내가 이해한 부분 
1) 최소 값을 갖게 하려면 덧셈 진행 -> 이후 뺄셈 진행 되어야 한다.
해보고자 했던 부분 
배열에 담아서 조건문으로 계산을 할 수 있을 것이다 -> 구현 실패 
구글링 했던 부분 
StringTokenizer 의 hashmoreToken 코드 ==> 사용할 수 있는 토큰이 더 존재하는 확인  기능 
구글링으로 이해 했던 부분
Tokenizer & while문으로 금방 확인할 수 있었다.
공항 (미제출)
=> [10일차] 신영제_BOJ_코테뿌셔_3

day11/BOJ_14889_스타트와링크/BOJ_14889_스타트와링크_신영제.java
- 스타트와 링크 (18296KB, 404ms)
1) 조합을 사용 팀을 선정 합니다. 팀이 다 만들 어 졌다면 격차를 줄일 함수로 이동합니다.
2) team_sum함수에 들어와 스타트 팀과 링크 팀 합산 진행을 합니다 -> 이후 최소값을 찾습니다.
- 테트로미노 (접근X) - 미제출 죄송합니다..
=> [11일차] 신영제_BOJ_코테뿌셔_4

day12/BOJ_14499_주사위굴리기/BOJ_14499_주사위굴리기_신영제.java, day12/BOJ_2468_안전영역/BOJ_2468_안전영역_신영제.java
2468 안전영역(19076KB 284ms)
1) 영역의 개수를 체크
2) 물에 잠기지 않는 지점들이 위, 아래, 왼쪽, 오른쪽 인접해 있으므로 4방 탐색 확인
3) 인접 영역의 최대 개수 만큼 침수가 가능하고, 아무 지역도 물에 잠기지 않을 수 있다. => 0부터 최대 크기만큼 반복하여 최대값 확인 
4) DFS 방법으로 조건을 만족할 때 까지 반복 (탐색 시작전 cnt ++)
14499 주사위 굴리기 (14896KB 184ms)
1) 이동한 칸에 쓰여있는 숫자가 '0'이면 -> 주사위 바닥의 숫자가 칸에 복사
2) 이동한 칸에 숫자가 있으면 -> 주사위 바닥이 흡수 + 칸은 '0'으로 변경
3) 이동 방향 동 서 북 남 에 맞게 탐색 방향 지정하여 조건 만족 시 search로 이동
3) 주사위 특성 1=6, 2=5, 3=4 
4) 동쪽(1) 으로 주사위가 이동할 경우 dice[1]값은 dice[3]의 값으로 변경 -- 이러한 규칙을 모두 적용하여 case문 활용
=> [12일차] 신영제_BOJ_코테뿌셔_5

day12/BOJ_14499_주사위굴리기/BOJ_14499_주사위굴리기_어정윤.java, day12/BOJ_2468_안전영역/BOJ_2468_안전영역_어정윤.java, day12/BOJ_2468_안전영역/BOJ_2468_안전영역_어정윤_BFS.java
=> [12일차] 어정윤_BOJ_코테뿌셔_5

day13/BOJ_12904_A와B/BOJ_12904_A와B_신영제.java
12904_A와B (15904KB 136ms)
(1)  T를 기준으로 시작한다.
(2)  T를 A를 만났을 경우, B를 만났을 경우 조건 을 걸어준다.
(3) 뒤부터 제거 한다. 
(4) 길이와 문자가 같다면 출력.
-수정-
(S를 기준으로 한다면 A를 추가) -> 반대로 T는 제거
(1). T의 맨 끝 글자가 A 일 경우 맨 끝 글자를 제거 합니다. 
(2) T의 맨 끝 글자가  B일 경우 T를 뒤집어 줍니다 + 맨 끝 글자를 제거 합니다. 
(3) (1)과 (2)를 반복하며 S와 T길이가 같을 경우 -> S와 T의 문자가 같은지 확인 합니다. 
16234_인구이동 미제출 죄송합니다ㅠㅠ..
=> [13일차] 신영제_BOJ_코테뿌셔_6

day13/BOJ_12904_A와B/BOJ_12904_A와B_신현국.java
=> [13일차] 신현국_BOJ_코테뿌셔_6

day14/BOJ_3190_뱀/BOJ_3190_뱀_신현국.java
=> [14일차] 신현국_BOJ_코테뿌셔_7

day14/BOJ_1167_트리의지름/BOJ_1167_트리의지름_어정윤.java, day14/BOJ_3190_뱀/BOJ_3190_뱀_어정윤.java
=> [14일차] 어정윤_BOJ_코테뿌셔_7

day15/BOJ_14891_톱니바퀴/BOJ_14891_톱니바퀴_어정윤.java
=> [15일차] 어정윤_BOJ_코테뿌셔_8

day15/BOJ_14891_톱니바퀴/BOJ_14891_톱니바퀴_김선후.java
1번 문제 톱니바퀴  / 메모리 14484KB 시간 128ms
풀이시간 56분 42초
* 문제를 접근법을 생각하는 시간보다 문제 자체의 지문을 이해하는데 시간이 굉장히 오래 걸렸습니다.
* 결국 두 톱니바퀴간의 연결부위가 같냐 다르냐로 회전여부를 정해준다는 말을 이해하는데 오래 걸렸고 입력받는 정보들을 이해하는데 시간이 걸렸습니다.
Solution 1.
1. 톱니바퀴 2차원 배열 gear[i][j]에 i는 톱니바퀴 번호 j는 톱니바퀴 상태를 입력 받는다.
2. 회전 횟수 K만큼 반복문을 돌아가면서 해당 톱니바퀴번호에 대한 회전방향 dir배열을 초기화해준다.
3. 톱니바퀴의 왼쪽과 오른쪽 방향의 회전방향을 체크해주고 dir배열을 입력해준다.
4. dir배열이 완성되면 모든 톱니바퀴를 지정된 방향으로 회전시켜준다. 회전이 끝나면 K번만큼 1번으로 돌아가서 반복한다.
5. 톱니바퀴 번호에 맞게끔 ans의 결과에 더해준다.
=> [15일차] 김선후_BOJ_코테뿌셔_8

day15/BOJ_14891_톱니바퀴/BOJ_14891_톱니바퀴_신현국.java
=> [15일차] 신현국_BOJ_코테뿌셔_8

day14/BOJ_1167_트리의지름/BOJ_1167_트리의지름_신영제_미완성.java, day14/BOJ_3190_뱀/BOJ_3190_뱀_신영제.java
3190_뱀(14348KB 140ms)
1) 뱀이 있는곳 = 2, 사과가 있는  곳 = 1, 아무것도 없는 곳 = 0
2) 뱀의 시작점은 1,1 이므로 2로 초기화  
3) 시간이 지나면 이동방향  바꿈.
4) 몸길이를 늘려 머리를 다음칸에 위치하도록 함.
5) 범위를 벗어나거나, 자기 몸에 부딪히면 종료.
6) 뱀이 이동한 위치에 사과가 있다면 꼬리 유지,  사과의 위치를 머리위치로 덮은다음 머리 추가
7) 사과가 없다면 꼬리가 위치한 곳 0으로 변경
8) 게임 종료할 때까지 cnt를 증가시켜주며 반복.
BOJ_1167 ( 구현 실현 X...)
1) 정점의 지름길이를 구하는 것 
2) 정점과 정점사이의 간선수를 파악 최장 거리를 확인. 
3) 임의의 두점 이라 하였으므로 아무 정점을 선택 해도 최장 거리를 확인 해야함
막힌 부분 -> DFS방식으로 풀어보고자 하였지만 '임의의 두점' 을 어떠한 방식으로 구현해야 할지 모르겠습니다
가장 기초적인 초기 인접행렬 방식으로 구현 이후에 방법을 아직 잘 모르겠습니다! ㅠㅠ
=> [14일차] 신영제_BOJ_코테뿌셔_7

day15/BOJ_14891_톱니바퀴/BOJ_14891_톱니바퀴_신영제.java
14891_톱니바퀴 (14244KB 128ms)
1) 톱니바퀴 방향 결정을 위해 회전 방향의 정보를 담는다.
2) 방향을 한번 받을때마다 좌측, 우측의 톱니의 회전 방향을 검사. 
3) 극이 같다면 회전 하지 않으므로 무시함
4) 좌우측 방향 검사를 끝냈으면  모든톱니에 대하여 각 회전 방향에 맞게 회전을 시킴
5) 모든 톱니바퀴가 돌아 갔다면 12시방향 [0]번째 배열의 값을 꺼내와 합 하여 결과 출력.
=> [15일차] 신영제_BOJ_코테뿌셔_8

day16/BOJ_15685_드래곤커브/BOJ_15685_드래곤커브_신현국.java, day16/BOJ_17951_흩날리는시험지속에서내평점이느껴진거야/BOJ_17951_흩날리는시험지속에서내평점이느껴진거야_신현국.java
=> [16일차] 신현국_BOJ_코테뿌셔_9

day16/BOJ_15685_드래곤커브/BOJ_15685_드래곤커브_어정윤.java
=> [16일차] 어정윤_BOJ_코테뿌셔_9

day16/BOJ_15685_드래곤커브/BOJ_15685_드래곤커브_신영제.java, day16/BOJ_17951_흩날리는시험지속에서내평점이느껴진거야/BOJ_17951_흩날리는시험지속에내평점이느껴진거야_신영제.java
1) 분류를 확인 했습니다.
2) 이분탐색 이론에 대하여 공부를 하였습니다. 
3) 오름차순 정렬하여 low + high가 아닌 현재 순서 그대로 K개의 그룹으로 나눠야 했습니다.
4) 현재 그대로에서 high값을 모두 더해주었습니다.
5) 최소값을 뽑아야 하므로 low값을 출력 해야합니다 -> low를 조절해가며 진행 해야합니다.
6) mid값을 가지고 arr배열을 계속 더해가며 작업을 해야하는지에 대한 구현이 어려웠습니다. 
1) 0 : 우 1 : 상 2 :좌 3 : 하 
2) 전 세대에서 그린 방향에서 역순으로 진행하면서 반시계 방향으로 돌립니다.
3) 처음 0세대를 리스트배열에 저장을 하며 세대만큼 반복을 돌린후 반시계 방향만큼 저장을 합니다. 
4) 이후 문제에 대한 접근을 잘 하지 못하겠습니다 ㅠㅠ...
=> [16일차] 신영제_BOJ_코테뿌셔_9

day17/BOJ_2262_토너먼트만들기/BOJ_2262_토너먼트만들기_신현국.java, day17/BOJ_2579_계단오르기/BOJ_2579_계단오르기_신현국.java
=> [17일차] 신현국_BOJ_코테뿌셔_10

day17/BOJ_14501_퇴사/BOJ_14501_퇴사_어정윤.java
=> [17일차] 어정윤_BOJ_코테뿌셔_10

day17/BOJ_14501_퇴사/BOJ_14501_퇴사.java, day17/BOJ_2262_토너먼트만들기/BOJ_2262_토너먼트만들기_신영제.java, day17/BOJ_2579_계단오르기/BOJ_2579_계단오르기_신영제.java
BOJ_14501_퇴사(14336KB 192ms)___DFS__부분 구글링
- 최고의 금액을  만들어야 하므로  전체조건을 다 돌려봐야 합니다.
- 처음 방문 배열을 만들어 기존DFS대로 시도를 했지만  전체 탐색을 하는데 실패하여 구글링 했습니다.
- DFS 조건을 현재 상담을 하였으면 상담기간과 금액을 넣어 DFS를 반복하고
- 다른 경우의 수를 반복하기 위해 다음날을 넣어  DFS 반복을 진행하되 금액을 넣지않고
-  퇴사날짜와 x가 같아질때의 금액을 결과를 출력합니다.
BOJ_2579_계단오르기(14224KB 124ms)
- 계단은 연속으로 3칸이상 오를수 없습니다.
- 이를 참고 하여 i = 3부터 실행 하여
- 동적테이블D[i]에 D[i-2] 번째 있는 값과  D[i-3] +arr[i-1])값중 높은 값을 선택합니다 
(D = 최대값이 들어갈 곳,  arr = 계단 정보 )
- 현재 위치한 계단을 더해  넣어줍니다.
- D[2] = arr[1]+arr[2] 를 했을 떄 ArrayIndexOutOf 에러가 발생 -> 질문 검색 : N이 1일때 발생되는 오류
- if(N >=2)로 해결
BOJ_2262_토너먼트만들기(14308KB 124ms) _ 문제해결방법 구글링
- 그리디 알고리즘의 분류를 보고 그리디정의에 대해서 재공부를 먼저 했습니다.
- 그 시간중 가장 최적의 값을 만들어야 했습니다.
- 우승자는 항상 1번인걸 먼저 생각했습니다.
- ( 인터넷 검색 ) 가장 큰 (Rank가 가장낮은) 사람을 찾아 좌, 우 사람중 차이가 적은사람과 경기 진행 
=> 랭크 차이가 많이나면 경기를 많이 해야한다는 …
=> [17일차] 신영제_BOJ_코테뿌셔_10

day18/BOJ_11053_가장긴증가하는부분수열/BOJ_11053_가장긴증가하는부분수열_어정윤.java, day18/BOJ_17404_RGB거리2/BOJ_17404_RGB거리2_어정윤.java, day18/BOJ_21610_마법사상어와비바라기/BOJ_21610_마법사상어와비바라기_어정윤.java
=> [18일차] 어정윤_BOJ_코테뿌셔_11

day19/BOJ_11404_플로이드/BOJ_11404_플로이드_어정윤.java, day19/BOJ_15684_사다리조작/BOJ_15684_사다리조작_어정윤.java, day19/BOJ_9440_숫자더하기/BOJ_9440_숫자더하기_어정윤.java
=> [19일차] 어정윤_BOJ_코테뿌셔_12

day19/BOJ_11404_플로이드/BOJ_11404_플로이드_김선후.java, day19/BOJ_15684_사다리조작/BOJ_15684_사다리조작_김선후.java, day19/BOJ_9440_숫자더하기/BOJ_9440_숫자더하기_김선후.java
1번 문제 숫자 더하기
메모리 14072KB 시간 120ms
풀이시간 1시간 34분
* 숫자들의 조합으로 두개의 숫자를 만들어야 한다.
* 간단하게 생각해보면 총 숫자의 개수에서 반을 나눈 두 숫자의 합이 최종결과값이 가장작다. 총 숫자 개수가 홀수인지 짝수인지 분기점.
* 두 숫자의 합이 최소가 되게 하려면 또다시 각 숫자의 조합을 최대한 작게해야한다.
* 자릿수가 낮을수록 큰 숫자를 배치해야 한다. => 가장 큰 자릿수에 가장 작은 숫자를 선택해야한다. 주의점 첫자리 0은 오면 안된다.
* 입력받은 숫자들을 오름차순 정렬하면 먼저 뽑히는 숫자가 더 작은 숫자로 들어간다.
* 0의 개수+2개(첫번째 자리에 올 숫자 두개)만큼 쉬프트를 고려해야함.
* 복수의 요소를 배열내에서 쉬프트 하는 방법을 알고자 쉬프트 관련 메소드를 구글링
* Solution 1.
1. 입력을 받을 때 개수를 시행 횟수를 모르므로 while 반복문을 사용해서 받는다. 마지막으로 받는 문자가 0이고 문자열개수가 1개면 반복문 종료
2. 오름차순 시 0이 앞으로 가게 된다. 첫자리에 0이 올수 없으므로 0의 개수만큼 숫자배열을 이동시켜야한다.
3. 정렬과정과 0의 쉬프트과정이 끝나면 앞에오는 숫자와 뒤에오는 숫자를 숫자배열에서 번갈아가면서 꺼낸후 두 수를 더한다.
2번 문제 플로이드
메모리 43460KB 시간 456ms
풀이시간 41분 12초
* 간단하게 플로이드 워샬 알고리즘만 사용하면 풀리는 문제인 줄 알았으나 도중에 고쳐야 할 것이 참으로 많았다.
* Solution 1.
1. 자기 자신으로 향하는 경우의 비용을 0으로 처리하고 …
=> [19일차] 김선후_BOJ_코테뿌셔_12

day20/BOJ_17140_이차원배열과연산/BOJ_17140_이차원배열과연산_신영제.java, day20/BOJ_1890_점프/BOJ_1890_점프_신영제.java
BOJ_1890_점프(14336KB 124ms) 
1) 점프의 진행방향은 언제나 왼->오 방향, 위->아래 방향으로 진행이 된다고 합니다.
2) 진행 방향에 맞춰 동적테이블 입력 또한 오른쪽, 아래로 진행을 합니다. 
3) 오른쪽일 경우 j값을 변동, 아래쪽일 경우 i값을 변동 이때 경계를 넘지 않는 값들만 이동 할 수 있게 합니다.
4) 경로의 갯수를 저장하는 (입력 배열과 동일한 크기의)동적테이블D[N][N] 을 생성합니다.
5) D[a][b] += D[i][j]는 a,b까지 올 수 있는 경로의 수를 계속 더해 줍니다.
6) 처음 맞닥뜨린 D[1][1]은 시작점이므로 무조건 갯수에 포함 되므로 1로 설정 합니다.
7) 동적테이블을 int형으로 설정을 했었는데 2의 63승 -1은 어마어마한 숫자 이므로 long형으로 변경 하여 해결 완료되었습니다.
BOJ_17140_이차원배열과연산(16940KB 212ms)
1) 배열A는 100을 넘어가는 경우는 무시한다고 하여 A의 크기를 100으로 만들어줍니다.
2) 배열A의 크기는 100으로 잡아 두었기 때문에 초기 row값과 col값을 3으로 설정합니다.
3) 시간이 100초를 넘어가게 되면(100번 이동되면) -1을 출력 해야하므로 time변수를 만들어줍니다.
4) R연산 C연산조건 만족시 해당 메소드를 실행 합니다.
5) 각 메소드당  등장횟수를 담을 1차원 배열을 만듭니다. 
6) 배열의 크기만큼 반복하여 등장횟수와 숫자를 A배열에 초기화 합니다.
7) 이러한 부분을 반복하며 k조건을 만족 할경우에 while문을 탈출하여 time을 출력합니다. …
=> [20일차] 신영제_BOJ_코테뿌셔_13

day20/BOJ_17140_이차원배열과연산/BOJ_17140_이차원배열과연산_신현국.java, day20/BOJ_1890_점프/BOJ_1890_점프_신현국.java, day20/BOJ_2110_공유기설치/BOJ_2110_공유기설치_신현국.java
=> [20일차] 신현국_BOJ_코테뿌셔_13

day20/BOJ_17140_이차원배열과연산/BOJ_17140_이차원배열과연산_어정윤.java
=> [20일차] 어정윤_BOJ_코테뿌셔_13

day21/BOJ_20058_마법사상어와파이어스톰/BOJ_20058_마법사상어와파이어스톰_신현국.java, day21/BOJ_9935_문자열폭발/BOJ_9935_문자열폭발_신현국.java
=> [21일차] 신현국_BOJ_코테뿌셔_14

day21/BOJ_20058_마법사상어와파이어스톰/BOJ_20058_마법사상어와파이어스톰_어정윤.java, day21/BOJ_9935_문자열폭발/BOJ_9935_문자열폭발_어정윤.java
=> [21일차] 어정윤_BOJ_코테뿌셔_14

day22/BOJ_12851_숨바꼭질2/BOJ_12851_숨바꼭질2_김선후.java, day22/BOJ_23288_주사위굴리기2/BOJ_23288_주사위굴리기2_김선후.java, day22/BOJ_2667_단지번호붙이기/BOJ_2667_단지번호붙이기_김선후.java
1번 문제 단지번호붙이기
메모리 14604KB 시간 132ms
Solution 1.
1. 지도에서 집이 있는 좌표(1)을 시작점으로 dfs 수행 시작
2. dfs 내부에서 사방탐색
3. 한번의 dfs 수행이 끝나면 하나의 연결덩어리가 완성되므로 단지 번호 ans값 증가
4. 최종 단지 번호 수만큼의 크기를 지닌 단지 개수 체크 배열 생성
5. 완탐을 통해서 맵 좌표가 0이 아닌곳을 해당좌표의 값을 인덱스로 개수 증가
6. 배열 오름차순 정렬 후 시작 인덱스 1번을 기준으로 최종 단지 번호만큼 단지 개수 출력 
풀이시간 42분 12초
2번 문제 숨바꼭질 2
메모리 67580KB 시간 232ms
Solution 1.
1. 최단경로(최단시간)? => bfs
2. 현재좌표와 현재시간을 제어할 수 있는 Node 클래스 선언
3. 해당 좌표의 방문처리를 방문한 시간으로서 체크할 수 있는 isVisitedByTime 1차원 int 배열 선언
4. 해당 좌표에 방문할 시 동일한 시간으로 방문하는 경우는 큐에 넣는다. 그보다 더 늦은 시간에 도착하는 경우는 제외
5. 도착한 시간을 비교해서 최단시간이면 caseCnt 증가해주며 큐가 빌때까지 수행해주면 된다.
풀이시간 42분 16초
3번 문제 주사위 굴리기 2
메모리 35620KB 시간 224ms
* 저번 주사위 굴리기 1문제의 응용문제. 이번에는 Dice 클래스를 따로 객체로서 제어함.
* 또 Point를 사용했다가 정말 영문모를 출력값 오류로 인해 그냥 Node 클래스를 따로 선언함.
* 어지간해선 Point 사용을 하지 않거나 좌표를 y, x 가 아닌 x, y로 사용 …
=> [22일차] 김선후_BOJ_코테뿌셔_15

day22/BOJ_12851_숨바꼭질2/BOJ_12851_숨바꼭질2_신영제.java, day22/BOJ_2667_단지번호붙이기/BOJ_2667_단지번호붙이기_신영제.java
BOJ_2667_단지번호붙이기(14272KB 140ms)
1) 문제의 그림을 보고 1이 이어질 때 까지  탐색을 진행해야 됨을 확인 했습니다.
2) DFS탐색을 준비 하였고 탐색 조건 아래 1이 연속되는 부분을 위해 count와 단지수를 확인하기 위한 cnt변수를 넣어줬습니다.
3) 삽입을 편하게 하기 위해 ArraysList를 사용하였습니다. 이후 오름차순 정렬을 실행해주었습니다. 
BOJ_23288_주사위굴리기2_실패 (문제 구현 실패 -> 100%구글링 -> 코드 이해50%) 
1) 혼자 이해한 부분 -> 주사위굴리기 1처럼 방향을 이동해가며 점수를 구하면 될 줄 알았습니다. 
2) 문제를 계속 읽어보면서 주사위 갱신? 하는 부분은 비슷할거 같았지만 쉽게 구현을 하지 못했습니다. 
3) 분류를 보고 구현과 그래프 문제임을 생각하며 점수합산 방식에 대하여 생각을 했지만 결국 인터넷 검색을 진행했습니다 ㅠㅠ.
4) https://ilmiodiario.tistory.com/m/160 <- 이분의 기술블로그를 보며 코드이해를 진행했습니다.
5) 주사위의 도면을 이용하여 풀었으며 행, 열의 기준을 잡아 주사위 값을 갱신 하였고 
6) 점수 획득 하는 부븐을 bfs를 통해 가져와 계산하는 방식으로 진행했습니다.
BOJ_12851_숨바꼭질(148248KB 416ms)
1) cnt 변수에 수빈이가 동생을 찾는 방법의 수를 작성할 준비를 합니다.
2) min 변수에 수빈이가 동생을 찾을 가장 빠른 시간을 작성할 준비를 합니다.
3) BFS 탐색을 진행하면서 Queue가 비어있을때까지 반복을 진행합니다. 
4) 수빈이의 …
=> [22일차] 신영제_BOJ_코테뿌셔_15

day22/BOJ_12851_숨바꼭질2/BOJ_12851_숨바꼭질2_신현국.java, day22/BOJ_23288_주사위굴리기2/BOJ_23288_주사위굴리기2_신현국.java, day22/BOJ_2667_단지번호붙이기/BOJ_2667_단지번호붙이기_신현국.java
=> [22일차] 신현국_BOJ_코테뿌셔_15

day22/BOJ_12851_숨바꼭질2/BOJ_12851_숨바꼭질2_어정윤.java, day22/BOJ_23288_주사위굴리기2/BOJ_23288_주사위굴리기2_어정윤.java, day22/BOJ_2667_단지번호붙이기/BOJ_2667_단지번호붙이기_어정윤.java
=> [22일차] 어정윤_BOJ_코테뿌셔_15

day23/BOJ_17142_연구소3/BOJ_17142_연구소3_신영제.java, day23/BOJ_1922_네트워크연결/BOJ_1922_네트워크연결_신영제.java, day23/BOJ_2512_예산/BOJ_2512_예산_신영제.java
BOJ_1922_네트워크연결(50344KB 572ms)
1) 가중치가 있는 그래프 탐색이므로 MST알고리즘을 확인했습니다. 
2) 크루스칼 알고리즘을 적용하고자 했습니다.
3) 간선의 정보를 arr배열에 담고나서 오름차순 정렬을 합니다.
4) 싸이클 형성하지 않는 간선을 선택하기 위해 parent배열에 정보들을 담습니다.
5) 정비가 끝났으면 낮은비용부터 크루스칼 알고리즘을 진행합니다.
6) UnionFind를 이용하여 서로 다른 집합이며 사이클이 형성되지 않는다면 값을 합쳐 나가고, 같은 집합으로 만듭니다. 
BOJ_2512_예산(15736KB 176ms)
1) 각 지방의 예산이 0원 ~ 최대높은지방의 금액까지 받을수 있습니다.
2) 이분탐색을 실시 했습니다. 
3) 예산들중 최대값을 뽑아내야 하므로 low <= high만큼 반복을 돌리며 진행합니다.
4) 지방의 요청이 OK되는 곳에 지방의 금액을 sum변수에 넣고, 세금에 비해 높은 요청이면 세금만 우선 sum에 넣습니다.
5) 예산이 초과한다면 high값을 조정합니다, 초과를 하지 않았다면 예산의 최대치를 뽑아내어 출력합니다. 
BOJ_17142_연구소3(문제이해O, 구현 50% -> 검색 -> 이해)
1) 연구소 문제와 비슷한 분류로 인하여DFS와 BFS를 이용하여 접근해보고자 했습니다 -> 바이러스활성 개수 체크 DFS, 뻗어나가는거 BFS
2) M개의 활성상태를 충족 시켰다면 활성 상태BFS로 가서 조건에 따라 탐색을 진행하려 했습니다.
3) 전체적인 틀을 잡고 세세한 조건을 확인 하는데 시간의 추가  최소시간 카운트 같은 구현에 한계를 느껴 …
=> [23일차] 신영제_BOJ_코테뿌셔_16

day24/BOJ_1513_경로찾기/BOJ_1513_경로찾기_신현국.java, day24/BOJ_21608_상어초등학교/BOJ_21608_상어초등학교_신현국.java
=> [24일차] 신현국_BOJ_코테뿌셔_17

day24/BOJ_21608_상어초등학교/BOJ_21608_상어초등학교_어정윤.java
=> [24일차] 어정윤_BOJ_코테뿌셔_17

day25/Programmers_2020_Kakao_문자열압축/Programmers_2020_Kakao_문자열압축_어정윤.java, day25/Programmers_2021_Kakao_신규아이디추천/Programmers_2021_Kakao_신규아이디추천_어정윤.java
=> [25일차] 어정윤_Programmers_코테뿌셔_18

day25/Programmers_2020_Kakao_문자열압축/Programmers_2020_kakao_문자열압축_김선후.java
1번 문제 신규 아이디 추천
* 풀이실패
* 문자열 메서드와 정규식을 이용해서 풀어야하는 문제로서 접근.
* 너무 다양한 종류의 문자들이 섞여있어서 기존에 이해하고 있던 방식으로는 문자열 처리에 어려움을 느낌.
* 문자열 메소드 혹은 정규식에 대한 복습 및 이해도 부족으로 문제 풀이 접근 실패.
2번 문제 문자열압축
Solution 1.
1. 주어진 문자열 s 길이의 반부터 길이 1까지 문자열을 자르는 단위길이 leng을 줄여나가며 압축된 문자열 길이 확인.
2. 반복문을 돌리면서 current문자열과 next문자열을 구하고 비교한다.
3. 해당문자열이 반복된 횟수 cnt를 업데이트하던중 next에 반복되지 않은 새로운 문자열이 나올시 기존 cnt와 current를 res문자열에 담기.
4. 잘려진 s의 마지막으로 남은 여분 문자열 next를 별도로 res에 담기.
5. answer 최솟값 대소비교 후 반환.
풀이시간 58분 14초
=> [25일차] 김선후_Programmers_코테뿌셔_18

day25/Programmers_2021_Kakao_신규아이디추천/Programmers_2021_Kakao_신규아이디추천_신현국.java
=> [25일차] 신현국_Programmers_코테뿌셔_18

day25/Programmers_2020_Kakao_문자열압축/Programmers_2020_Kakao_문자열압축_신영제.java, day25/Programmers_2021_Kakao_신규아이디추천/Programmers_2021_Kakao_신규아이디추천_신영제.java
PRO_신규아이디추천
1. 단계별로 구현하는 문제를 확인 했습니다. 
2. 2단계 ~ 6단계 까지 특정 단어가 제거가 되므로 아무것도 없음으로 변경하면 되어 replace를 생각했습니다. 
2. replaceAll + 정규 표현식을 활용하여 단계별로 구현을 할 수 있음을 캐치했습니다.
3. 정규표현식 사용이 어색하여 옆에 정규표현식 규칙을 띄어놓고 함께 풀이 하였습니다. 
PRO_문자열압축 (쪼개어 길이 구하는 부분 구글링.)
1. 문자열의 절반을 넘어가면 패턴의 최대길이를 만들지 못하므로 반복이 되지 않습니다.
2. 절반의 변수를 생성하여 그만큼만 반복을 돌게합니다.
3. 문자열 절반의 길이만큼 반복을 돌면서 문자열을 비교해 갑니다.
4. sum으로 압축할 수 있으면 cnt를 추가해가며 압축을 하지못한다면 newStr에 업데이트를 합니다.
5. 이후 다음 문자를 대입해 과정을 반복하여 길이를 비교해갑니다.
=> [25일차] 신영제_Programmers_코테뿌셔_18

day26/Programmers_2022_Kakao_주차요금계산/Programmers_2022_Kakao_주차요금계산_김선후.java, day26/Programmers_summer&winter_internship_배달/Programmers_summer_winter_internship_배달_김선후.java
1번 문제 배달
* 1번 마을에서 K이하의 시간으로 배달을 갈 수 있는 마을의 개수를 구하는 문제.
* 1번 마을에서 각 마을간의 최단경로(최단시간)을 구해서 K시간 이하가 몇 개 있는지를 구하는 문제.
Solution 1.
1. 간선리스트와 최단경로배열 초기화.
2. 최단경로배열이 갱신되지 않았을 때 무한대로 초기화.
3. 간선리스트에 간선 정보 갱신
4. 1번도시의 최단경로비용을 0으로 갱신(자기 자신으로 돌아오는 최단 경로는 0이므로)
5. 다익스트라 알고리즘
6. 1번마을에서 K이하 비용인 도시 개수만큼 정답수 증가 후 반환.
풀이시간 52분 48초
2번 문제 주차요금계산
* 자동차 번호를 key값으로 놓고 입차시간과 출차시간을 계산하고 관리한다.
* 두개의 맵을 사용하는데 차량 번호가 작은 자동차부터 정렬해야 하므로 하나는 Treemap 선언
* records 배열 기준 In이 들어오면 Hashmap out이 들어오면 Treemap에 분으로 치환한 시간 저장
* out이 들어올 때 기존 in에 있는 데이터 삭제
* 마지막까지 in에 남아있는 데이터는 23시 59분 기준 계산
* 최종적으로 트리맵 out에 key값 차번호 value값 사용한 시간이 담겨져 있음.
* 초과된 시간이 0분보다 높다면 올림처리. Math.ceil 사용
풀이시간 1시간 12분 14초
=> [26일차] 김선후_Programmers_코테뿌셔_19

day26/Programmers_2022_Kakao_주차요금계산/Programmers_2022_Kakao_주차요금계산_신영제.java, day26/Programmers_summer&winter_internship_배달/Programmers_summer&winter_internship_배달_신영제.java
PRO_주차요금계산 ( 접근 실패 --  map 사용법 공부로 대신하였습니다. ) 
1. 차량번호 오름차순으로 출력 하므로 차량번호 별로 묶어서 계산하는 식으로 생각 했습니다.
2. 잘못된 생각임을 알아차리고 자료구조사용에 대한 접근을 시도 했지만 논리적인 접근이 많이 부족했습니다. 
3. 문제에 대한 구현이 어려워 검색을 하였는데 MAP자료구조를 사용 하였습니다. 
4. MAP에 대한 지식이 많이 부족해서 코드를 분석하면서 MAP 함수에대해 공부하는 시간을 가졌습니다! 
PRO_ 배달 
1. 음의 간선이 존재X, 가중치O 
2. 최단거리를 구하는 로직이므로 다익스트라 알고리즘을 생각했습니다. 
2. 처음 시작하는 노드1에서 거리는 0으로 초기화 하여 시작 합니다. 
4. K비용만큼 갈 수 있는 마을의 수를 출력합니다.
=> [26일차] 신영제_Programmers_코테뿌셔_19

day27/BOJ_1707_이분그래프/BOJ_1707_이분그래프_김선후.java
1번 문제 이분그래프
메모리 272356KB 시간 952ms
* 이분 그래프가 뭘 의미하는건지 문제지문만으로는 이해가 안되서 구글링을 하였습니다.
* 이분 그래프란 각 정점을 두가지 색(그룹)으로 나누었을때 인접한 두 정점(노드)의 색(그룹)이 다른 그래프를 말합니다.
Solution 1.
1. 두 개의 그룹을 만든다. int배열로 1과 -1로 구분.
2. 그래프의 인접요소를 bfs탐색을 통해 차례로 방문하면서 해당정점이 한번도 색칠(그룹화)되지 않을경우 현재정점과 다른색(그룹)으로 칠한다.
3. 이미 그룹화 되어있는 정점(노드)라면 현재 정점과 비교한다.
4. 그룹이 같다면 빠져나오면서 NO를 출력한다.
5. 모든 탐색이 종료될때까지 NO가 출력되지 않았다면 YES를 출력한다.
풀이시간 52분 14초(이분그래프 해설참조)
2번 문제 게리맨더링2
문제이해에 난해함으로 인해 접근실패
=> [27일차] 김선후_BOJ_코테뿌셔_20

day27/BOJ_1707_이분그래프/BOJ_1707_이분그래프_신현국.java, day27/BOJ_17779_게리맨더링2/BOJ_17779_게리맨더링2_신현국.java
=>  [27일차] 신현국_BOJ_코테뿌셔_20

day27/BOJ_1707_이분그래프/BOJ_1707_이분그래프_신영제.java
BOJ_1707_이분그래프_신영제(271872KB 1124ms)
1. 정점들을 연결할 list를 생성하여 연결 합니다.
2. 이분 그래프는 연결될 곳이 같은 값이면 안됩니다. 
3. 방문할 정점들을 0으로 초기화 해주고, 먼저 만나는 곳을 1로 해줍니다.
4. 연결된 정점들을 확인하며 추가하며 반복이 끝나면 YES 그전에 만나는정점이 있으면 NO를 출력합니다.
BOJ_17779_게리맨더링2 (구현 실패)
1. d1, d2의 조합을 구하고 이에 따라 나올수 있는 조합을 구합니다.
2. 조건에 따라 경계를 지정하고 구역을 나누며 번호를 지정 하면 됩니다.
3. 이러한 조건들에 따라 작성을 하면 되는듯한 문제지만 깊이있게 문제에 대한 접근이 안되어 구현실패 하였습니다.
=> [27일차] 신영제_BOJ_코테뿌셔_20

day28/BOJ_1874_스택수열/BOJ_1874_스택수열_김선후.java, day28/Programmers_2020_Kakao_자물쇠와열쇠/Programmers_2020_kakao_자물쇠와열쇠_김선후.java
1번 문제 스택 수열
메모리 28344KB 시간 396ms
* 1~n까지의 값을 push와 pop으로 수열을 만드는 문제
* 테케 1은 N이 8이므로 1~8까지의 수열, 원하는 형태는 4,3,6,8,7,5,2,1
* 처음으로 4가 나와야하므로 1234가 스택에 push되어 있어야 한다 ++++
* 배열인덱스 0번값과 스택의 마지막입력값이 같으므로 pop ++++-
* 그다음 인덱스 1번값 3이 스택의 마지막값 3과 같으므로 pop ++++--
* 이런식으로 수열이 성립되거나 되지않을때까지 반복문을 돌린후 최종 결과물을 출력하는 문제
Solution 1.
1. 현재 비교할 배열의 인덱스와 입력값을 초기화 한 후 배열에 원하는 수열 입력
2. 반복문을 수행하면서 스택의 push pop 연산 수행
3. 반복문이 종료한 뒤의 최종 idx값이 N과 같다면 끝까지 연산이 수행되었으므로 스트링빌더에 저장된 문자열 출력 아니라면 NO
풀이시간 34분 12초
2번 문제 자물쇠와 열쇠 (단독 구현 실패)
* 문제 풀이 접근법 자체는 금방 떠올랐으나 원하는 기능을 구현하는데 어려움을 겪어서 해당 기능을 구현하기 위해서 구글링을 하였습니다.
* 구글링 결과 이미지 패딩 알고리즘이라는 것이 있어서 해당 알고리즘을 이용하여 구현하였습니다.
* 처음에 접근한 방법은 key 혹은 lock을 시작점(0,0)에 두고 브루트포스 알고리즘을 통해 홈에 맞출때까지 진행하는 방식입니다.
* 끝까지 맞는 부분이 없으면 key 혹은 lock 을 90도 회전한 후 다시 브루트포스 탐색을 진행하는 방식으로 접근법 자체는 쉬웠던 문제 같습니다.
* 다만 …
=> [28일차] 김선후_BOJ_Programmers_코테뿌셔_21

day29/BOJ_3273_두수의합/BOJ_3273_두수의합_어정윤.java
=> [29일차] 어정윤_BOJ_코테뿌셔_22

day29/BOJ_3273_두수의합/BOJ_3273_두수의합_김선후.java
두 수의 합
* 투 포인터 알고리즘의 전형적인 문제.
* 투 포인터와 이분 탐색의 차이점
* 투 포인터 : 시작과 끝, 최악의 경우 O(N), 정렬이 필요할 때도 필요치 않을 때도 있다.
* 이분 탐색 : mid를 활용, 매 탐색마다 범위를 절반으로 좁혀나감 O(logN), 정렬되어 있다는 가정
* Solution 1.
1. 배열 입력 받기
2. 목표 수 입력 받기
3. 배열 정렬
4. 배열의 시작인덱스와 끝인덱스를 더하기
5. 목표 수를 조건으로 인덱스 조정
6. 정답 쌍 출력
메모리 27160 시간 376ms
=> [29일차] 김선후_BOJ_코테뿌셔_22

day30/BOJ_1107_리모컨/BOJ_1107_리모컨_김선후.java
리모컨
메모리 16876KB 시간 216ms
* 완전탐색으로 0번채널부터 50만채널까지의 모든 경우에서 해당하는 최솟값을 비교한다.
Solution 1.
1. 입력을 받는다.
2. 고장난 버튼 개수 여부를 따진다.
3. 고장난 버튼이 있다면 고장버튼 배열을 갱신한다.
4. +-로만 움직이는 최솟값을 구한다.
5. 50만까지의 채널중에서 목표채널을 이동하기 위한 최단채널 숫자버튼 누르는 수를 구한다.
6. 목표채널까지 해당채널에서 +-로만 움직이는 수를 구한다.
7. 최솟값을 비교하여 갱신한다.
8. 최솟값 출력
=> [30일차] 김선후_BOJ_코테뿌셔_23

day30/BOJ_1107_리모컨/BOJ_1107_리모컨_신영제.java
1. 고장난 숫자를 담기 위해 Boolean배열을 생성하여 True로 값을 넣어 주었습니다.
2. 가장 먼저 버튼으로만 이동하는 경우를 구합니다. ( - 값이 나올 수 있으므로 절대값 함수 사용 ) 
3. 버튼으로만 누를 경우의 최대 경우의 수를 가지고 반복문을 실행 합니다.
4. 입력이 가능한 숫자와 버튼의 이동 횟수를 더한 값과  (2)와 비교하여 최소 값을 도출합니다.
=> [30일차] 신영제_BOJ_코테뿌셔_23

day30/BOJ_1107_리모컨/BOJ_1107_리모컨_어정윤.java
=> [30일차] 어정윤_BOJ_코테뿌셔_23

day31/BOJ_2146_다리만들기/BOJ_2146_다리만들기_김선후.java
1번 문제 다리 만들기
* 메모리 296032KB 시간 1348ms
* 풀이시간 1시간 24분 32초
* 특정 덩어리(그룹) 탐색, 최단경로 =>bfs/dfs 사용 유추
* 섬을 찾은 후 섬의 덩어리(그룹)별로 넘버링을 해준 후 각 섬마다의 최단 경로를 찾는 문제임을 파악.
Solution 1.
1. 입력하기(2차원배열 맵, 섬넘버링 초기화, 정답값 초기화)
2. 육지(섬)찾기
3. 육지(섬) 넘버링
4. 정답(최단경로다리 놓을 위치)찾기
5. 정답만들기(최단경로다리 생성 및 갱신)
6. 출력하기
=> [31일차] 김선후_BOJ_코테뿌셔_24

day31/BOJ_2146_다리만들기/BOJ_2146_다리만들기_어정윤.java
=> [31일차] 어정윤_BOJ_코테뿌셔_24

day31/BOJ_2146_다리만들기/BOJ_2146_다리만들기_신영제.java
1. 모든 육지는 1로 주어지므로 각 섬마다 분리를 해줘야 최단거리 구할때 쉬울꺼라 판단 했습니다. 
2. 식별이 된 섬끼리 최단 거리를 구합니다. 
3. (1)에 대한 그래프 탐색을 완료 후 (2) 에 대한 조건을 생각하다 실패 했습니다.
=> [31일차] 신영제_BOJ_코테뿌셔_24

day32/BOJ_20437_문자열게임2/BOJ_20437_문자열게임2_신영제.java
---
1. 문제이해에 대한 검색 활용 하였습니다. 
2. 입력받은 문자열의 개수를 알파벳 크기만큼 배열에 담습니다. -> K개 이하면 continue하기 위함
3. 2중 for문을 돌려 K개를 만족시키는 알파벳을 찾아 count를 증가 시켜줍니다.
4.  count와 K가 일치 하다면 min값과 max값을 구하고 해당 반복문을 탈출하여 다른 탐색을 시도합니다.
5. 첫번째의 반복문이 끝날때까지 탐색을 진행 했다면 min값과 max값이 정해져 있습니다.
=> [32일차] 신영제_BOJ_코테뿌셔_25

day33/BOJ_16918_봄버맨/BOJ_16918_봄버맨_어정윤.java
=> [33일차] 어정윤_BOJ_코테뿌셔_26

day33/BOJ_16918_봄버맨/BOJ_16918_봄버맨_신영제.java
BOJ_16918_봄버맨 ( 15872KB 268ms )
0. 같이 공부하던 친구에게 도움을 조금 얻었습니다!
1. 시간이 1일 경우 무시가 됩니다.
2. 시간이 짝수일 경우 폭탄이 추가가 되며 홀수일 경우 3초전 폭탄이 터집니다
3. 짝수함수를 생성하여 3초뒤에 터질거라고 현재 시간 + 3을 해줍니다.
4. 폭탄이 터지는 함수를 생성하여 값을 처리 합니다
=> [33일차] 신영제_BOJ_코테뿌셔_26

day33/BOJ_16918_봄버맨/BOJ_16918_봄버맨_김선후.java
봄버맨
* 메모리 108828KB 시간 316ms
Solution 1.
* 시뮬레이션 문제
1. 초기 맵 입력
2. 각 시간마다의 붐버맨 행동(2초단위로 폭탄 설치 3초주기로 폭탄 폭발)
3. N초까지 반복
4. 최종 맵 상태 갱신
5. 맵 출력
* 풀이시간 52분 17초
=> [33일차] 김선후_BOJ_코테뿌셔_26

day34/BOJ_1012_유기농배추/BOJ_1012_유기농배추_어정윤.java
=> [34일차] 어정윤_BOJ_코테뿌셔_27

day34/BOJ_1012_유기농배추/BOJ_1012_유기농배추_김선후.java
유기농 배추
메모리 15840KB 시간 168ms
* 완전탐색, bfs/dfs 문제
* 2차원 배열을 탐색하면서 인접한 배추 덩어리 영역 개수를 구하는 문제
Solution 1.
1. 배추 밭 2차원 배열 map 입력 (배추가 있는 좌표는 1)
2. map 전체를 탐색하면서 배추가 있는 장소이면서 한번도 방문한적 없으면 dfs탐색 후 영역 수 1 증가
3. 완전탐색이 끝난 이후 최종 영역 개수 출력
풀이시간 34분 18초
=> [34일차] 김선후_BOJ_코테뿌셔_27

day34/BOJ_1012_유기농배추/BOJ_1012_유기농배추_신영제.java
1. 배추가 모여있는 지역을 탐색하기 위해 배열에서 1인 지역을 탐색 합니다.
2. 1인 지역을 찾았다면 주변을 탐색하여 보호구역을 탐색 합니다.
3. 보호구역에 다녀옴을 식별 하기위해 방문 배열을 만들어 확인 합니다. 
4. 보호구역을 확인 했으면 지렁이가 몇마리 필요한지 확인하기 위해 카운트 + 1을 합니다.
5. 모든 지역을 탐색 했으면 카운트의 갯수를 출력합니다.
=> [34일차] 신영제_BOJ_코테뿌셔_27

day35/Programmers_summer&winter_internship_영어끝말잇기/Programmers_summer&winter_internship_영어끝말잇기_어정윤.java
=> [35일차] 어정윤_Programmers_코테뿌셔_28

day35/Programmers_summer&winter_internship_영어끝말잇기/Programmers_summer&winter_internship_영어끝말잇기_정세미.java
=> [35일차] 정세미_Programmers_코테뿌셔_28

day35/Programmers_summer&winter_internship_영어끝말잇기/Programmers_summer&winter_internship_영어끝말잇기_신영제.java
1. 단어들의 길이만큼 배열을 돌며 탈락자를 찾을 준비를 합니다.
2. 해당 list가 시작이 된다면 이전 단어를 저장 합니다.
3. 탈락조건인 동일한 단어, 끝단어와 일치하지 않은 단어시작을 설정하여 해당하는 사람이 있다면 배열에 삽입후 return 합니다.
=> [35일차] 신영제_Programmers_코테뿌셔_28

day36/BOJ_6087_레이저통신/BOJ_6087_레이저통신_정세미.java
=> [36일차] 정세미_BOJ_코테뿌셔_29

day37/Programmers_2022_Kakao_양과늑대/Programmers_2022_Kakao_양과늑대_어정윤.java
=> [37일차] 어정윤_Programmers_코테뿌셔_30

day37/Programmers_2022_Kakao_양과늑대/Programmers_2022_Kakao_양과늑대_정세미.java
=> [37일차] 정세미_Programmers_코테뿌셔_30

day37/Programmers_2022_Kakao_양과늑대/Programmers_2022_Kakao_양과늑대_신영제_이해X.java
문제 접근 이해를 하지 못하여 https://tech.kakao.com/2022/01/14/2022-kakao-recruitment-round-1/ 
해당 링크 풀이를 보며 학습 하였습니다.
이해가 어려웠던 부분
1. 방문 했던 곳을 재 방문 체크
2. 늑대와 양의 관리
3. 그래프만 확인하여 DFS접근 생각X 
문제 해석
1. 양, 늑대, 현재위치, 다음 방문 노드, 위치의 종류 를 DFS로 접근 합니다.
2. 해당 위치에 양, 늑대를 확인하여 추가해줍니다. 
3. 양과 늑대가 같아질 경우 종료 합니다.
4. 현재 위치를 제외한 방문 했던곳 까지 추가하여 다음 DFS를 시도 합니다.
5. 반복하여 값을 갱신하여 양의 최대로 구할 수 있는 값을 출력합니다.
=> [37일차] 신영제_Programmers_코테뿌셔_30

day38/BOJ_1080_행렬/BOJ_1080_행렬_정세미.java
=> [38일차] 정세미_BOJ_코테뿌셔_31

day38/BOJ_1080_행렬/BOJ_1080_행렬_신영제.java
- 변화 전 행렬 (beforeArr), 변화 후(afterArr) 행렬을 입력 받습니다.
- 3*3 크기 만큼 변화 시키므로 첫 번째 값이 변한다면 3*3이 변하므로 첫 값을 활용합니다.
- before 과 after 원소가 일치하지 않다면 cnt +1 해주고 첫 값을 제외한 나머지 값들도 변경시켜줍니다.
- 변화를 끝내고 값이 일치하지 않는다면 -1을 리턴 해주고 출력 해줍니다.
=> [38일차] 신영제_BOJ_코테뿌셔_31

day38/BOJ_1080_행렬/BOJ_1080_행렬_어정윤.java
=> [38일차] 어정윤_BOJ_코테뿌셔_31

day39/BOJ_3055_탈출/BOJ_3055_탈출_어정윤.java
=> [39일차] 어정윤_BOJ_코테뿌셔_32

day39/BOJ_3055_탈출/BOJ_3055_탈출_정세미.java
- 메모리: 16276KB, 시간: 164ms
- 풀이 방법
1. 고슴도치 시작 위치와 물 시작위치 저장
2. 고슴도치가 갈 수 있는 위치를 시작위치부터 bfs
- 고슴도치 queue 갱신 전 물 이동 bfs 우선 실행
3. 도착지에 도착했다면 step을 출력하고 종료
=> [39일차] 정세미_BOJ_코테뿌셔_32

day39/BOJ_3055_탈출/BOJ_3055_탈출_신영제.java
BOJ_3055 (14280KB 128ms)
---
1. 초기 물과 두더지를 큐에 저장 합니다. 
2. 매 분이 증가 될 때마다 인접한 물도 접근 할 수 없으므로 물 부터 증가 시킵니다.
2-1. 증가되는 물 좌표를 물 큐에 저장 합니다.
3. 증가된 후 두더지를 이동 시킵니다.
3-1. 다음 이동할 곳이 빈칸이라면 다음 두더지 좌표를 두더지 큐에 저장 합니다.
3-2. 다음 이동할 곳이 도착 장소라면 true를 return해줍니다.
4. 두더지가 비어있지 않은 상황에 true값이 return 되면 도착한것이므로 cnt를 출력해주고 종료합니다.
5. 두더지가 비어있는 상황에 false값이 return 되면 갈 수 있는 곳이 없으므로 KAKTUS를 출력해주고 종료합니다.
=> [39일차] 신영제_BOJ_코테뿌셔_32 

day40/BOJ_2062_돌다리건너기/BOJ_2602_돌다리건너기_신영제_검색.java
접근 DP에 대한 이해를 하지못하여 인터넷을 보며 학습 했습니다. [ 정확히 이해 불가 ] 
DP의 점화식을 사용하여 현재 다리 i에 있는 글자가 두루마리 j위치의 글자와 일치하는 경우의 점화식과
일치하지 않는 점화식을 작성하여 인덱스를 구합니다.
학습 =>  https://mytodays.tistory.com/40
=> [40일차] 신영제_BOJ_코테뿌셔_33

day40/BOJ_2062_돌다리건너기/BOJ_2602_돌다리건너기_김선후.java
돌다리 건너기 (실패)
* dp 문제라는 것을 깨닫기 까지 2시간 가량 소모
* 완탐 실패
* 풀이 실패후 서칭 그러나 제대로 된 이해 불가
규칙은 총 5가지
1. 왼쪽에서 오른쪽으로 이동
2. 주어진 문자열에 적힌 순서대로 밟기
3. 돌다리 두 개를 번갈아 가면서 건너 뜀
4. 건너뛰는 칸 수는 무관
5. 한 칸 이상 오른쪽으로 이동.
Solution 1.
1. 입력값으로 초기화
2. 천사다리로 시작한 경우의 수와 악마다리로 시작한 이동 경우의 수를 더한다.
3. 이동 함수 진행
3.1 찾은 문자열 개수가 마법의 단어 개수와 같아지면 경우의 수 증가
3.2 현재 dp[찾은 문자열 개수][시작 위치][다리 타입]값이 0이 아니라면 같은 경우의 수가 존재하므로 그대로 반환
3.3 천사다리일경우 마법의단어[찾은 문자열 개수]==천사다리[시작 위치] 혹은 악마다리일때 다음 문자열 탐색으로 이동
3.4 그 동안의 경우의 수의 합을 dp[찾은 문자열 개수][시작 위치][다리 타입]에 반환
메모리 16480KB 시간 400ms
풀이 시간 2시간 52분 12초
=> [40일차] 김선후_BOJ_코테뿌셔_33

day40/BOJ_2062_돌다리건너기/BOJ_2062_돌다리건너기_정세미.java
=> [40일차] 정세미_BOJ_코테뿌셔_33

day40/BOJ_2062_돌다리건너기/BOJ_2062_돌다리건너기.java
=> [40일차] 어정윤_BOJ_코테뿌셔_33

day41/BOJ_2234_성곽/BOJ_2234_성곽_어정윤.java
=> [41일차] 어정윤_BOJ_코테뿌셔_34

day41/BOJ_2234_성곽/BOJ_2234_성곽_정세미.java
=> [41일차] 정세미_BOJ_코테뿌셔_34

day41/BOJ_2234_성곽/BOJ_2234_성곽_이길상.java
=> [41일차] 이길상_BOJ_코테뿌셔_34

day42/BOJ_12100_2048(Easy)/BOJ_12100_2048(Easy)_정세미.java
=> [42일차] 정세미_BOJ_코테뿌셔_35

day43/BOJ_14719_빗물/BOJ_14719_빗물_어정윤.java
=> [43일차] 어정윤_BOJ_코테뿌셔_36

day43/BOJ_14719_빗물/BOJ_14719_빗물_신영제.java
1. 현재 위치를 기준으로 왼쪽벽, 오른쪽벽 최대값 탐색하고 저장 합니다.
2. 현재 위치가 최대값들보다 크다면 패스 합니다.
3. 왼쪽과 오른쪽의 최대값들중 최소값만큼 물이 담기므로 최소값을 선별합니다.
4. 선별한 값과 현재 위치의 만큼 빼면 물이 찰 수 있는 양이므로 전체를 반복하며 빗물을 더해줍니다
=> [43일차] 신영제_BOJ_코테뿌셔_36

day44/BOJ_5972_택배배송/BOJ_5972_택배배송_정세미.java
=> [44일차] 정세미_BOJ_코테뿌셔_37

day44/BOJ_5972_택배배송/BOJ_5972_택배배송_어정윤.java
=> [44일차] 어정윤_BOJ_코테뿌셔_37

day45/BOJ_21944_문제추천시스템Version2/BOJ_21944_문제추천시스템Version2_신영제.java
BOJ_21944 (91424KB 1060MS)_ 구글링
1. 알고리즘별 분류를 해주어야 하기 때문에 클래스를 만들어 정렬을 해주어야 합니다.
2. 해당 명령어를 받아 처리 과정에서 자료구조에 대한 이해가 부족하여 인터넷 검색을 진행 했습니다.
3. 입력받은 값들을 case문을 통해 알고리즘 분류 처리를 해줍니다.
4. ceiling을 통해 지정된 객체값과 같은 값들중 가장 가까운 큰 객체값을 반환 합니다.
5. floor를 통해 지정된 객체값과 같은 값들중 가장 가까운 작은 값을 반환 합니다
=> [45일차] 신영제_BOJ_코테뿌셔_38

day45/BOJ_21944_문제추천시스템Version2/BOJ_21944_문제추천시스템Version2_정세미.java
=> [45일차] 정세미_BOJ_코테뿌셔_38

day45/BOJ_21944_문제추천시스템Version2/BOJ_21944_문제추천시스템Version2_김선후_구글링.java
문제 추천 시스템 Version 2
구글링
* 메모리 73096KB 시간 960ms
* Set과 Map 등의 자료구조 등을 이용해야 하는 문제인것은 문제의 제한을 보고 인지.
* 최악 P 100000 * L 100 * G 100을 * M 10000번을 탐색해야 할 수도 있는 경우 이기에 일반적인 순차탐색은 해결법에서 배제
* 키값을 통한 정보접근이 곧바로 가능한 Set과 Map을 통한 자료구조를 이용해 빠르게 정보에 대한 조회와 수정,추가,삭제가 필요한 문제임을 확인.
* 다만 Set과 Map의 지니고 있는 메서드들이 기억이 나지 않아 구글링.
* 추천리스트의 추가와 삭제, 조회 3가지를 비롯하여 총 5가지의 명령분기를 지니는 문제.
* 조회 3가지의 전제 조건과 삭제 조건 중 문제분류 G를 통한 분류와 난이도 L을 통한 분류, 아무상관없는 전체 분류와 P로 해당 문제의 L과 G의 접근에 사용할 자료구조가 필요.
Solution 1.
1. 문제의 번호, 난이도, 분류를 요소로 갖는 클래스 선언
2. 최초 입력값 초기화
3. 명령문 개수만큼 반복문 실행
4. 명령의 분기조건에 따른 조회,추가,삭제 실행
풀이시간 3시간 24분 12초
=> [45일차] 김선후_BOJ_코테뿌셔_38

day45/BOJ_21944_문제추천시스템Version2/BOJ_21944_문제추천시스템Version2_어정윤.java
=> [45일차] 어정윤_BOJ_코테뿌셔_38
