- day1/BOJ_1018_체스판다시칠하기/BOJ_1018_체스판다시칠하기_신현국.java
1. NxM 체스판에서 8x8로 탐색이 가능한 부분 완전 탐색 진행
2. 8x8 체스판의 왼쪽 상단이 'W' 시작하는 W case와 'B'로 시작하는 B case에 대해 탐색 진행
3. 완전 탐색으로 각 경우의 max 카운트를 저장
4. 64(8x8)에서 W case와 B case 중에 더 큰 값을 빼면 정답 도출
> [1일차] 신현국_BOJ_1018_체스판다시칠하기

- day3/BOJ_14696_딱지놀이/BOJ_14696_딱지놀이_김선후.java
- day3/BOJ_2477_참외밭/BOJ_2477_참외밭_김선후.java
- day3/BOJ_2491_수열/BOJ_2491_수열_김선후.java
- day3/BOJ_2669_직사각형네개의합집합면적구하기/BOJ_2669_직사각형네개의합집합면적구하기_김선후.java
1번 문제 직사각형 네개의 합집합의 면적 구하기
/*
* 예전에 과제에서 풀었던 색종이 문제의 용응문제라고 생각했고 풀었음.
* 시작 x,y 좌표를 끝 x,y좌표에서 빼주면 가로와 세로의 길이를 구할수 있다.
* 1~100까지의 좌표를 담을수 있도록 int[101][101]의 종이 2차원 배열을 만들고 
* 그 안에 시작 y,x좌표를 초기값으로 두고 가로와 세로길이만큼 종이면적을 체크해준다.
* 전체 종이 배열중에서 체크된곳에서만 cnt를 증가시켜준다.
*/
2번 문제 수열
/*
* 수열을 담을 배열 혹은 리스트를 담고 
* 현재인덱스의 값과 다음인덱스의 값이 >=, <관계 즉 내림차순일 때 정답값++, 혹은 1로 초기화
* 오름차순일 때는 <=, > 관계 일때 정답값++, 혹은 1로 초기화 
* 내림차순 오름차순을 각각 반복한 뒤에 최대 정닶값을 찾는다.
*/
3번 문제 참외밭
/*fail
* 북쪽 4번과 남쪽 3번은 y배열, 높이배열에 값을 저장해두고,
* 서쪽 2번과 동쪽 1번은 x배열, 가로배열에 값을 저장해둔다.
* 높이배열과 가로배열을 오름차순 혹은 내림차순으로 정렬한후 
* (max높이*max가로) - (min높이 * min가로)를 하면 참외밭의 넓이가 나온다.
* 넓이 * 참외밭 1m^2당 참외수를 곱하면 총 참외수가 나온다.
* 
* 정답풀이
* 각 변의 인덱스 0,1,2,3,4,5를 받고
* i번인덱스의 변*i+1의인덱스의 변의 각 사각형을 구한다.
* 사각형중 가장 큰 넓이를 지는것을 전체넓이로 두고
* 전체 사각형을 제외하고 각 사각형들의 총합은 구해야하는 넓이*3+파인부분의 넓이가 …
> [3일차] 김선후_BOJ_월말평가대비_2

- day3/BOJ_14696_딱지놀이/BOJ_14696_딱지놀이_박기윤.java
- day3/BOJ_2477_참외밭/BOJ_2477_참외밭_박기윤.java
- day3/BOJ_2491_수열/BOJ_2491_수열_박기윤.java
- day3/BOJ_2669_직사각형네개의합집합면적구하기/BOJ_2669_직사각형네개의합집합의면적구하기_박기윤.java
- BOJ_14696_딱지놀이
- 별→동그라미→네모→세모 순으로 개수를 확인해서, 특정 도형의 그림을 더 많이 갖고 있는 어린이가 있다면 해당 어린이 승. 세모의 개수까지 동일하다면 무승부 처리.
- BOJ_2477_참외밭
- 참외밭으로 가능한 모양은 ㄱ,┏, ┗, ┛4종류이다.
- 각 모양 별로 입력의 특징이 있다.
- ㄱ: 방향으로 1,3이 연속적으로 2번 주어진다. (ex) 3-1-3-1
- ┏: 방향으로 1,4가 연속적으로 2번 주어진다.
- ┗: 방향으로 2,4가 연속적으로 2번 주어진다.
- ┛: 방향으로 2,3이 연속적으로 2번 주어진다.
그렇기 때문에 방향의 입력값으로 참외밭의 모양을 알 수 있다.
- 참외밭의 모양은 항상 큰 사각형에서 작은 사각형을 뺀 모양이다.
→ 참외밭 면적=큰 사각형 면적-작은 사각형 면적
이를 구하기 위해서는 각 사각형의 가로, 세로 길이를 알아야 한다.
- 큰 사각형
가로: 동쪽 길이, 서쪽 길이 중 최댓값
세로: 북쪽 길이, 남쪽 길이 중 최댓값
- 작은 사각형
참외밭 모양 ㄱ을 예시로 들면
방향의 입력이 4-2-3-1-3-1이 주어지고 작은 사각형의 가로, 세로 길이는 반드시! 
가로: 2번(서쪽)으로 주어지는 수의 다음 다음 수→1로 주어지는 수
세로: 2번(서쪽)으로 주어지는 수의 다음 다음 다음 수→3으로 주어지는 수
(이건 그림을 그려보면 알 수 있습니다!)
길이를 알아냈으니 각각의 사각형 면적을 구해 큰 사각형에서 작은 사각형을 빼주면 참외밭의 면적이 되고, 여기에 면적 당 자라는 참외의 개수를 구하면 끝.
- BOJ_2491_수열
- 이전에 계산한 …
> [3일차] 박기윤_BOJ_월말평가대비_2

- day5/BOJ_2527_직사각형/BOJ_2527_직사각형_박기윤.java
- day5/BOJ_2559_수열/BOJ_2559_수열_박기윤.java
- day5/BOJ_2578_빙고/BOJ_2578_빙고_박기윤.java
- day5/BOJ_2628_종이자르기/BOJ_2628_종이자르기_박기윤.java
- 수열
1. 2xN 2차원 배열 생성 (0행: 입력값, 1행: 온도의 합을 저장)
2. N개의 수 중 연속된 K개의 합을 구하는 경우에, 더하기 연산은 총 N-K+1번 일어난다. 이 횟수만큼 반복문을 실행하고, 최대 온도 합이 나올 때마다 maxSum을 갱신한다. 
이 때, 연산의 수를 줄이기 위해, 반복문을 돌 때마다 K개의 수를 모두 돌면서 더하는 방식이 아닌, `이전 연산 결과 - 1일 전 온도 + (K-1)일 뒤 온도` 로 구한다.
- 종이자르기
1. rowList와 colList를 만들어 초기에는 0과 가로/세로의 길이를 넣는다.
2. 입력값을 읽으며, 가로로 자르는 점선은 rowList에, 세로로 자르는 점선은 colList에 점선 번호를 넣는다.
3. 두 리스트를 오름차순 정렬
4. 정렬을 했으니 각각의 가로, 세로 잘려진 길이는 (리스트의 i인덱스 - 리스트의 i-1인덱스)로 구할 수 있다.
5. 잘려진 가로, 세로 길이의 최댓값을 구해 두 수를 곱한 값을 출력한다.
- 빙고
1. 철수의 빙고판 2차원 배열은 boardInfo 객체를 담는다. 이는 빙고판 숫자 num과 그 숫자가 불려졌는지 isChecked를 멤버변수로 가지고 있다.
2. `playBingo` : 철수의 빙고 판에서 진행자가 부른 숫자를 탐색하여, 그 수가 있으면 getLine함수 호출
3. `getLine` : 현재 사회자가 부른 숫자로 인해 몇 개의 line이 형성되었는지를 반환하는 함수.
현재 위치 기준 대응되는 방향(상-하/좌-우/우상-좌하 등)을 탐색하기 위해 lineCheck함수를 호출한다. 서로 대응되는 방향을 …
> [5일차] 박기윤_BOJ_월말평가대비_4

- day8/BOJ_14502_연구소/BOJ_14502_연구소_박기윤.java
- day8/BOJ_18352_특정거리의도시찾기/BOJ_18352_특정거리의도시찾기_박기윤.java
- day8/BOJ_2210_숫자판점프/BOJ_2210_숫자판점프_박기윤.java
- day8/BOJ_4963_섬의개수/BOJ_4963_섬의개수_박기윤.java
- map 2차원 배열에 지도 저장
- for문에서 한 칸씩 탐색하며 그 칸이 섬이라면 checkIsland 호출, 바다이면 배열 값을 -1(CHECKED)로 바꿔 더 이상 탐색하지 않도록 처리
- `checkIsland` : 너비우선탐색으로 시작점에서 인접한 섬을 모두 탐색한다. 이 때 인접한 섬 또한 배열 값을 -1(CHECKED)로 바꿔 더 이상 탐색하지 않도록 처리. 시작점에서 인접한 섬을 모두 탐색하였다면 1을 반환한다.
- 반환된 1을 result에 누적 시키면, 최종 result 값이 섬의 개수이다.
- 숫자판을 board 2차원 배열에 저장
- 모든 칸을 시작 좌표로 makeNum 함수를 호출
- `makeNum`
- 깊이우선탐색으로 인접한 칸을 stringBuilder에 계속 쌓는다.
- 인접한 칸의 좌표와 count(현재 몇개의 수를 쌓았는지)를 매개변수로 넘기고, count값이 6이 되면 HashSet에 추가 후 return. (중복 수를 따로 처리하지 않기 위해 중복을 허용하지 않는 HashSet 자료구조 사용함).
- return 후 stringBuilder의 마지막 숫자 삭제 처리 후 앞선 과정을 다시 반복. (이 때 한번 거쳤던 칸을 다시 거치는 것을 허용하기 때문에 방문 처리는 하지 않아도 된다. )
- 최종적으로 hashSet의 크기가  만들 수 있는 수의 개수
- 간선 리스트 생성하여 입력 값을 넣는다.
- 출발 도시에서 특정 도시까지의 최소 비용을 저장할 minCost 배열 생성 후 Integer.MAX_VALUE값으로 초기화
- X를 시작점으로 `bfs` 함수 호출하여 …
> [8일차] 박기윤_BOJ_코테뿌셔_1

- day11/BOJ_14500_테트로미노/BOJ_14500_테트로미노_김선후.java
- day11/BOJ_14889_스타트와링크/BOJ_14889_스타트와링크_김선후.java
1번 문제 테트로미노 메모리 : 45860KB , 시간 : 1016ms 성공
1. 0차 예상 무작정 완전탐색을 돌릴경우 TLE가 발생할 가능성이 높다고 판단하여 배제. (시도는 해보지 않음) next step
2. 1차 풀이법 시도 1*4 긴작대기 케이스, 2*2 정사각형 케이스, 2*3 그외의 케이스로 세경우로 나눠 완탐을 돌렸으나 TLE로 실패. next step
3. 2차 풀이법 시도 dfs를 사용하면 깊이 4일때 블록별 max값을 구해서 풀수 있는 문제라고 생각하였으나 ㅗ자 모양의 튀어나온 부분에서 기본적인 dfs형식으론 풀 수 없어서 실패. next step
4. 3차 풀이법 시도 ㅗ자 모양 블록을 제외한 다른경우는 전부 dfs를 수행하고 ㅗ자만 따로 ㅗ,ㅜ ㅓ,ㅏ 경우별 탐색을 만들어서 풀어봄. 성공
2번 문제 스타트와 링크 메모리 : 18824KB , 시간 : 384ms 성공
시간제한 2초 = O(풀이) 약 2억
N=20 스타트팀 혹은 링크팀에 선택하는가 하지않는가 2가지 경우 조합경우 수 최악 O(2^20) 약 100만가량
따라서 조합사용 가능
1. 조합 알고리즘을 사용하여
2. 각 팀의 수 N/2 (N이짝수) 조합선택카운트 N/2가 될때
3. 선택된사람팀(스타트팀)과 비선택사람팀(링크팀)별 능력치를 더한 후 최솟값을 구하기 (getDiff() 메소드호출)
> [11일차] 김선후_BOJ_코테뿌셔_4

- day12/BOJ_14499_주사위굴리기/BOJ_14499_주사위굴리기_김선후.java
- day12/BOJ_2468_안전영역/BOJ_2468_안전영역_김선후.java
1번 안전 영역 / 메모리 18932KB 시간 256ms 성공
* 문제를 보자마자 예전에 연구실문제라던가 이 문제와 흡사한 덩어리를 구하는 문제가 생각나서 
바로 dfs문제인걸 눈치챘습니다. 
* 이 문제에서의 문제 해결과정은 다음과 같습니다. 
1. 물이 높이에 따라서 침수가 되는 지역과 안전영역을 구분해주고
2. 그에 따라서 dfs가 한번 수행을 마칠때마다 횟수를 모든 물의높이에서 구해준 뒤
3. 그중에서 가장 최댓값을 구하면 됩니다.
2번 문제 주사위 굴리기 / 메모리 14580KB , 시간 : 140ms 성공
* 각 주사위의 방향인덱스는 변하지 않는다. 
ex) 1번인덱스는 무조건 TOP 6번인덱스는 무조건 BOTTOM
* 4방탐색을 위한 delta 1차원 배열의 크기를 5로 지정해준다.(인덱스 1부터 사용하기 때문에)
* solution 1 currentDice 클래스를 만들어서 현재 주사위의 좌표와 속성들을 매 순간마다 갱신해준다.
백준 테케 4에서 원점으로 돌아오고 다음 동작이 원하는 동작이 나오지 않아서 실패 ㅠㅠ- 원인을 찾지 못했음.
* solution 2 tempDice 배열에 dice배열을 복사하여 넣어준 뒤 각 명령에 맞게 주사위의 값과 바닥을 갱신해준다.
1. 명령의 방향에 따라서 주사위를 굴린다.
2.  해당좌표의 map값과 주사위의 BOTTOM값을 비교한다.
2-1.해당좌표의 map값이 0이라면 그 순간의 주사위 BOTTOM 값을 map에 저장한다.
2-2.해당좌표의 map값이 0이 아니라면 그 값을 주사위의 BOTTOM에 저장하고 map을 0으로 초기화한다.
3. 주사위의 …
> [12일차] 김선후_BOJ_코테뿌셔_5

- day14/BOJ_1167_트리의지름/BOJ_1167_트리의지름_김선후.java
- day14/BOJ_3190_뱀/BOJ_3190_뱀_김선후.java
1번 트리의 지름 / 메모리 : 98516KB 시간 : 996ms 성공 풀이시간 2시간 14분 13초
트리와 bfs dfs 가중치와 관련해서 기억이 흐릿해져서 예전에 라이브 시간때 배웠던 내용들을 복습하는 시간을 가졌습니다.
트리에 존재하는 모든 경로 중 가장 긴것의 길이가 트리의 지름
* Solution 1.
1. 각 정점에 대한 인접리스트와 간선가중치를 저장하는 배열을 만든다.
2. dfs 탐색을 수행하여 각 정점에 해당하는 가중치 값들을 계속 더해가며 모든 정점에서의 거리의 최대값을 구한다.
실패 TLE(시간초과) 모든 정점에서 전부 dfs수행이 일어나게 되면서 시간초과가 일어난다.
* Solution 2.
1. 가장 긴 지름을 만드는 정점 A와 정점 B가 있다고 가정했을 때, 임의의 노드 1개(여기선 루트정점)에서 가장 먼 정점은 정점 A거나 B다.
2. dfs나 bfs를 수행해서 루트로부터 가장 긴 거리를 지닌 정점 A혹은 B를 찾아낸다.
3. 해당 정점을 기준으로 다시 bfs/dfs를 수행하면 나머지 정점 한개를 구할 수 있다.
2번 뱀 / 메모리 14640KB 시간 132ms 성공 풀이시간 : 1시간 28분 54초
문제 접근법 자체가 어렵지는 않은 문제였으나 시뮬레이션 문제가 늘 그렇듯 생각을 순차적으로 코드로 옮기는 과정이 어려웠습니다.
뱀의 이동과정을 나타내는데 큐와 덱을 사용하면 쉽게 구현할 수 있겠다라는 생각이 들었고 시간별로 종속된 방향전환 값을 담을 수 있는 자료구조가 하나 필요하다고 생각했습니다.
키값에 따른 값을 담는 Map과 기본적인 List 그리고 Que 이렇게 세가지가 …
> [14일차] 김선후_BOJ_코테뿌셔_7

- day16/BOJ_15685_드래곤커브/BOJ_15685_드래곤커브_김선후.java
- day16/BOJ_17951_흩날리는시험지속에서내평점이느껴진거야/BOJ_17951_흩날리는시험지속에서내평점이느껴진거야_김선후_실패및구글링이해불가.java
1번 문제 드래곤 커브 
메모리 : 14408KB 시간 : 140ms
추가 내용 메모리 : 14436 시간 : 132ms
풀이시간 1시간 4분 06초
* 입력으로 드래곤커브의 시작 좌표, 시작 방향, 세대가 주어진다.
* 이전 세대에서 시계방향으로 90도 만큼 회전한 모양이 다음 세대가 된다.
* 방향 0 1 2 3 우 상 좌 하 (방향+1)%4=반시계방향 90도 회전
* 주어진 예시에서 n세대인 드래곤 커브의 방향리스트는
세대 0 [0]
세대 1 [0, 1]
세대 2 [0, 1, 2, 1]
세대 3 [0, 1, 2, 1, 2, 3, 2, 1]
* 이전 세대의 방향 리스트를 역순으로 탐색한뒤 (방향+1)%4의 방향이 다음 선분을 그리게 되는 방향이 된다.
Solution 1.
1. 드래곤커브의 정보를 입력받는다.
2. 드래곤커브의 개수만큼 맵에 점들을 표시한다.
2-1. 0세대는 자기 자신의 좌표와 시작좌표+시작방향좌표를 찍는다.
2-2. 1세대부터는 이전 세대의 방향좌표 리스트를 역순으로 탐색하며 세대수만큼 반복해서 점을 찍는다.
3. 맵을 탐색하며 점이 찍혀있는 부분이 네 꼭짓점 전체를 이루고 있으면 정답카운트를 증가시킨다.
2번 문제 흩날리는 시험지 속에서 내 평점이 느껴진거야
* 문제풀이 실패 
* 처음에는 순열, 조합, 부분집합 문제라고 생각했으나 문제의 조건을 자세히 살펴보면 시험지의 순서는 이미 정해져 있다.
* 이 문제에서 구해야할 것은 그룹별 최소점수의 최댓값이다.
* 완탐을 돌리면 최악의 경우 O(10만 * 10만)이 나오므로 사용해선 안된다는 것 까진 알 수 있었다.
* log의 …
> [16일차] 김선후_BOJ_코테뿌셔_9

- day17/BOJ_14501_퇴사/BOJ_14501_퇴사_김선후.java
- day17/BOJ_2262_토너먼트만들기/BOJ_2262_토너먼트만들기_김선후.java
- day17/BOJ_2579_계단오르기/BOJ_2579_계단오르기_김선후.java
1번 문제 토너먼트 만들기  
메모리 14416KB 시간 132ms
풀이시간 2시간 52분
* 처음에 문제 예시를 보고 B예시의 답이 11이라는 점에서 아무리 봐도 10이 나와야 하지 않은지 의문이 들어서 문제에 대해서 파악하는데 오래걸렸습니다.
* 1시간동안 문제에 대한 명확한 접근법을 찾을수 없어서 알고리즘 분류를 보고서 그리드로 풀어야 한다는 것을 알았습니다.
* 처음에는 모든 선수들을 3명씩 끊은후 중앙에서 양쪽의 차이를 비교한 후 부전승으로 오를 선수를 결정한 뒤 랭킹차를 더해나가는 식으로 접근을 해보았으나 양쪽 선수들과의 랭킹차이가 같은 경우의 예외처리를 두는것이 복잡해서 해결하지 못하였습니다.
* 문제에서 주어진 절차를 생각해보았을때 매칭이 된 두 선수 중에서 랭킹이 더 높은(숫자가 낮은) 선수가 무조건 승리합니다.
* 선수들이 매칭되는 순서는 변하지 않는 경우 랭킹이 가장 높은 선수들순서대로 토너먼트 순서를 진행한다고 한다면 양쪽에서 랭킹 차이가 적은 선수들을 선택해도 갈수록 점차 이전 선수보다 더 랭킹이 낮은 선수들과 경기가 진행되므로 랭킹 차가 점점 더 커집니다.
* 반대로 랭킹이 가장 낮은 선수부터 토너먼트 순서를 진행시킨다면 랭킹이 낮은 선수는 반드시 경기에서 승리하지 못하기 때문에 그 선수를 남은 선수목록에서 제외시키며 진행할수 있게됩니다.
Solution 1.
1. 선수들을 순서대로 담을 수 있는 리스트 선언
2. 가장 랭킹이 낮은 선수의 랭크를 담을 변수 lastRank에 선언된선수수(=가장낮은랭킹)를 저장
3. 리스트를 탐색하기위한 인덱스 변수에 랭킹이 가장 낮은 선수의 인덱스를 …
> [17일차] 김선후_BOJ_코테뿌셔_10

- day20/BOJ_17140_이차원배열과연산/BOJ_17140_이차원배열과연산_김선후_fail.java
- day20/BOJ_1890_점프/BOJ_1890_점프_김선후.java
- day20/BOJ_2110_공유기설치/BOJ_2110_공유기설치_김선후.java
1번 문제 점프
메모리 14368KB 시간 136ms
풀이시간 1시간 2분
* 지문을 읽으면서 dfs로 해결을 할 생각을 했다가 답이 최악 2^63-1이 나오므로 일반적인 dfs로는 시간초과가 확정.
* dp와 dfs를 섞어서 사용하여 중복 구간에 대한 연산을 지울 필요가 있음(메모이제이션)
Solution 1.
1. 2차원 배열 map에 입력을 받고 같은 배열크기의 long타입 dp를 초기화한다.(미연결상태 표시를 위해 -1로 초기화)
2. 초기좌표로부터 dfs 연산 수행
2-1. dp[y][x]의 방문처리를 위해 0으로 초기화
2-2. 다음에 갈수있는 좌표는 현재좌표의 값을 각 y,x좌표에 더한 값이다.
2-3. 만약 ny, nx가 N(배열 크기)보다 커지면 0을 반환한다.(즉 해당좌표의 dfs연산값은 0(이동실패)이다)
2-4. 만약 아래나 옆으로 갈수 있다면 현재 연결 처리된 dp[y][x]와 dp[y][x]+dfs(다음좌표) 중 큰것을 dp[y][x]로 갱신한다.
2-5. dp[y][x]를 반환한다.
2-6. 만약 dp[y][x]가 이미 연결된 곳이라면 dp[y][x]를 반환한다.
2-7. 만약 y x의 좌표가 끝점이라면 1을 반환한다. (dfs 더하기 연산에서 끝까지 연결된 경우만 더해주는 경우)
2번 문제 공유기 설치
메모리 28988KB 시간 300ms
풀이시간 32분 53초
* 입력값이 최대 10억(=일반적인 완전탐색에만 평균 1초)가 걸리므로 브루트포스는 배제해야 할 것 같았습니다.
* 문제에서 원하는 결과를 도출하기 위해서는 C개의 한정된 공유기 개수로 현재 입력된 전체 길이에서 거리 …
> [20일차] 김선후_BOJ_코테뿌셔_13

- day21/BOJ_20058_마법사상어와파이어스톰/BOJ_20058_마법사상어와파이어스톰_김선후.java
- day21/BOJ_20058_마법사상어와파이어스톰/BOJ_20058_마법사상어와파이어스톰_김선후_실패.java
- day21/BOJ_9935_문자열폭발/BOJ_9935_문자열폭발_김선후.java
1번 문제 문자열 폭발
메모리 22736KB 시간 320ms
풀이시간 56분 42초
* 문자열의 재입력과 삭제과정이 한번의 문자열탐색과정에서 동시에 일어나야 한다.(메모리 초과때문)
* Solution 1(메모리초과 실패 아마 시간초과도 나왔을거라 생각됨).
1. split()메서드를 이용하여 String배열에 나눠서 입력
2. 나누어진 문자열배열을 다시 하나의 문자열로 합침.
3. 문자열배열의 길이가 1이고 입력문자열의 길이가 0이거나 최종문자열일 경우 반복문 종료.
4. 문자열길이에 따라서 정답값 출력
* 실패 이유 분석
* 최악의 경우 문자열 aaaabbbb 폭탄 ab일경우 한번의 반복문에서 제거되는 문자열 길이는 2밖에 안됨.
* 문자열 길이를 한번 탐색하는데 O(N)이 걸리며 -2씩 계속해서 탐색을 재반복할경우 N까지의 합연산(N(N+1)/2)
* N의 최대길이는 100만이므로 100만의 제곱이 나온 순간부터 시간초과가 나왔을 거라고 예상됨.
Solution 2
1. 문자열 길이만큼 탐색을 진행하며 하나의 문자를 탐색할때마다 현재탐색중인 인덱스 길이 증가.
2. 폭탄을 사용할수 있는 조건이 만족되면 현재까지 누적된 인덱스 길이에서 폭탄 길이만큼 제거
3. 갱신된 인덱스 길이에서 다시 문자를 입력받는것을 반복.
4. 문자배열을 String.valueOf()메서드를 사용하여 다시 하나의 문자열로 반환.
2번 문제 마법사 상어와 파이어스톰
메모리 38724KB 시간 340ms
* Solution 1.(실패 => 고치는데 성공)
1. 2^N만큼 맵배열을 받는다.
2. 맵배열 전체를 마법단계L을 기준으로 …
> [21일차] 김선후_BOJ_코테뿌셔_14

- day21/BOJ_20058_마법사상어와파이어스톰/BOJ_20058_마법사상어와파이어스톰_신영제_실패.java
- day21/BOJ_9935_문자열폭발/BOJ_9935_문자열폭발_신영제.java
BOJ_20058_마법사상어와파이어스톰(회전 하는부분 이해, 녹이기 X -> 2시간 문제 접근 -> 규칙 -> 구현X)
1) 문제를 읽고 큰 틀로 나누어 90도 회전 하는 방향 (구현) + 얼음 칸수 구하기(DFS) + 얼음 녹이기 (BFS) 하는 방식으로 접근 해보고자 했습니다. 
2) 얼음 칸수는 배열을 돌아다니며 1이상인 것들의 사방을 연결하고, 가장큰 뭉치의 개수(count)를 더합니다.
3) 전체 돌아다니며 가장 큰값을 갱신해 나갑니다.
4) 얼음 녹이기는 사방 얼음이 3개이상 인접해이지 않은 칸은 얼음의 양이 1줄어듭니다. 
5) (4)-> 얼음이 없는 칸이 2개 이상일 경우 얼음의 양이 1줄어듭니다.
6) 얼음 칸수 구하기는 구현 + BFS이후 탐색을 시작하는거라 구현이 가능했지만(정확한지는 모르겠습니다 ㅠㅠ) 
7) 회전하는 방향의 규칙?을 찾지 못하여 구현하지 못하였습니다. 
8) 그나마 찾은 규칙이 L2 를 기준으로 0,0 -> 0,2 | 0,1 -> 1,2 | 0,2 -> 2,2 | 1,0 -> 0,1 | 1,1 -> 1,1 | 1,2 -> 2,1 이러한 방식으로 이동하였습니다.
BOJ_9935_문자열 폭발(62500KB 492ms)
1) 문자열을 하나씩 스택에 넣으면서 폭발물과 비교 해보고자 했습니다.
2) 스택의 최상단 값과 폭발물의 마지막과 일치 하다면 boolean변수를 만들어 참으로 만들어놉니다.
3) 이후 문자열의 값과 폭발물의 값과 같은지 비교를 하는 반복문을 생성 합니다.
4) 일치 하지않는다면 제거 대상에서 제외가 되므로 boolean변수를 거짓으로 변경하고 해당 스택 …
> [21일차] 신영제_BOJ_코테뿌셔_14

- day23/BOJ_17142_연구소3/BOJ_17142_연구소3_김선후.java
- day23/BOJ_1922_네트워크연결/BOJ_1922_네트워크연결_김선후.java
- day23/BOJ_2512_예산/BOJ_2512_예산_김선후.java
1번 문제 네트워크 연결
메모리 46775KB 시간 488ms
* 가중치가 존재하며 모든 간선을 최소 비용으로 연결 해야할 때 적용할 알고리즘은 MST가 있다.
* 또한 a b 정점과 b c 정점이 연결 상태라면 a c 가 연결 상태가 된다는 것은 b의 최상위 부모가 a이고 b와 c가 연결 상태라면 c의 부모는 a로 바꾸는 식으로 연결상태를 표현
* 유니온파인드를 응용할 수 있는 문제다.
Solution 1.
1. 모든 정점을 최소비용으로 연결
2. 크루스칼 알고리즘 적용
3. 가중치를 기준으로 오름차순 정렬 (우선순위 큐 적용)
4. 가중치가 가장 낮은 두 정점(가장 먼저 빠져 나온 큐) 선택
5. 두 정점의 부모가 같은지 다른지 판별 후 다르면 같은 부모로 결합(union-find)
6. union-find가 사용될때마다 해당 간선을 선택했다는 의미로 해당 간선의 가중치를 증가시킨다.
7. 모든 큐가 빌 경우 나오게 된 가중치의 합이 최소비용이 된다(우선순위 큐로 오름차순을 하였기때문)
풀이시간 21분 1초
2번 문제 예산
메모리 16960KB 시간 192ms
* 기본적인 탐색을 진행한다면 최악 탐색을 한번 하는데만 10억=1초가 걸린다. => 일반적인 완탐 문제가 아님.
* 가상의 목표 점수를 구해야 함. => 이진탐색
Solution 1.
1. 입력을 받는다.
2. 이진 탐색을 위해서 지방배열을 오름차순으로 정렬.
3. 모든 지방의 합이 주어진 상한선보다 작거나 같다면 지방예산 최댓값을 그대로 출력
4. 3의 조건을 만족하지 않다면 이진 탐색 수행
5. 지방예산이 목표예산보다 크다면 기준값을 현재 …
> [23일차] 김선후_BOJ_코테뿌셔_16

- day24/BOJ_1513_경로찾기/BOJ_1513_경로찾기_김선후.java
1번 문제 경로 찾기
메모리 49840KB 시간 272ms
* 크기가 N*M인 직사각형에서 오른쪽, 위쪽 방향으로만 움직이면서 문제의 수를 줄여나가는 dp형 문제
* 경로 개수의 경우의 수를 구하기 위해서 매 순간마다의 상태를 정의해줘야 한다.
* dp[y][x][현재 방문한 오락실 번호(마지막으로 들린 오락실 번호)][방문한 오락실 개수] = 경로의 수
* y,x 좌표에 도착했을 때 들렸던 오락실이 방문한 오락실 개수로 계산하고자 하면, 그 전에 들렸던 오락실의 번호보다 현재 오락실 번호가 더 커야하므로
* 매 상태마다 마지막에 들린 오락실의 번호를 저장해둘 필요성이 있어서 4차원 배열로 정의
* 점화식
* 현재 방문한 좌표가 오락실인 경우와 오락실이 아닌 경우로 나눈다.
* 오락실일 경우 방문한 오락실 개수를 증가시켜야 하며 방문한 오락실 번호보다 작은 오락실번호까지의 모든 방문 경우의 수를 더해줘야 한다.
* 오락실이 아닐 경우 별도의 계산 없이 아랫칸좌표와 왼쪽좌표가 지니고 있는 경우의 수를 더하면서 갱신 초기화 과정을 거친다.
* 매 연산 종료시점마다 mod=1000007로 나머지연산을 진행해야 하는 것을 놓치면 안된다.
Solution 1.
1. 입력을 받는다. dp배열의 최대 크기값은 51로 지정한다. (0부터 50까지 혹은 1부터 50까지가 최대 사용범위)
2. 1,1일때의 dp배열을 초기화 한다.
2-1. 만약 1,1 좌표가 오락실일 경우 각 번호에 맞는 상태에 초기화를 시키고 방문 오락실 개수를 1로 한다.
2-2. map배열에 오락실 번호를 초기화한다.
3. dp수행
3-1. 현재 방문 …
> [24일차] 김선후_BOJ_코테뿌셔_17

- day36/BOJ_6087_레이저통신/BOJ_6087_레이저통신_김선후.java
레이저 통신
* 메모리 67532KB 시간 384ms
* 최대 100*100 맵배열을 DFS로 탐색하고자 할 시 스택오버플로우의 위험성이 있어 BFS로 접근.
* H W 크기의 지도에서 C로 표시된 두 칸이 레이저를 쏠 수 있는 칸
* 빈 칸은 '.', 벽은 '*'
* 레이저가 발사되고 있는 도중 거울을 설치해서 방향 회전
* 두 C가 연결되는 경우의 수 중 거울 설치 개수의 최솟값을 구하는 문제.
Solution 1.
1. 맵을 입력 받은 2차원 char 배열 map과 방문체크 및 거울개수를 기록할 2차원 int 배열 isVisited 초기화.
2. 레이저 좌표의 시작점과 종료지점을 담아둘 리스트 lazor 초기화. 이때 레이저 좌표의 현상태를 나타내는 Position 클래스 필요.
3. 입력 받는 중 현재 맵배열에 입력될 문자가 'C'인 경우 lazor에 저장. 첫번째가 시작점 두번째가 종료점.
4. BFS 탐색을 통한 레이저 경로 탐색 및 거울 설치 시작.
5. 큐에 처음으로 넣을 값으로 레이저 시작점을 넣은 후 bfs 진행.
6. 현재 진행중인 큐의 Position이 레이저 종료점일 경우 정답값 비교 후 최솟값 갱신
7. 사방탐색을 진행하며 경계 및 벽을 만날시 다음 방향으로 전환.
8. 다음 레이저 방향이 현재 레이저 방향과 다르거나 종료점이 아니라면 거울 설치
9. 만일 이전에 다음 레이저 좌표에 방문한적이 있으며 그때 설치된 거울 수가 현재 설치된 거울 수 보다 작다면 거울설치 취소.
10. BFS 종료후 최솟값 출력
풀이시간 52분 12초
> [36일차] 김선후_BOJ_코테뿌셔_29

- day36/BOJ_6087_레이저통신/BOJ_6087_레이저통신_신영제_검색활용.java
0. 방향 전환 시 갱신 + 다익스트라 사용 인터넷 검색 
1. laser class를 사용하여 시작 레이저와 도착 레이저를 저장 합니다.
2. 처음에는 모든 방향으로 통신이 가능 하므로 -1로 저장 합니다.
3. 거울의 수를 갱신할 visit배열에 갱신이 계속되기 때문에
방문 배열을 작성하지 않고 무한대로 초기화합니다. 
4. 우선순위 큐를 사용 하여 거울 수가 더 적은 경우 갱신하여 큐에 추가합니다.
5. -1 이거나 현재 방향과 탐색방향이 다른경우 거울을 추가해야 하므로 거울 수를 더합니다.
내 생각 : 
1. 출발, 도착 C를 기준으로 모든 영역 탐색하여 최소값 식별합니다. 
2. 거울의 갯수를 추가할 방법이 떠오르지 않았습니다. 
3. BFS 탐색을 통해 모든 방향을 탐색 해보고자 했습니다.
4. ( 2 )의 구현이 생각이 안나 접근 방법을 본 후 다익스트라 학습 후 인터넷 검색하여 문제 이해를 취지로 학습 하였습니다.
> [36일차] 신영제_BOJ_코테뿌셔_29

- day39/BOJ_3055_탈출/BOJ_3055_탈출_김선후.java
탈출
메모리 14364 KB 시간 128 ms
* 동시간대에 별도의 두 곳에서 동시에 진행되는 BFS 문제
* 같은 시간에 같은 공간 내에서 동일한 회차로 진행
* 고슴도치가 이동할 수 없는 요소 (물+물 상하좌우+돌+굴)(+고슴도치가 지나온 자리(최소시간))
Solution 1.
1. 고슴도치 시작 지점, 도착 지점 좌표 맵핑.
2. 초기 물 좌표 큐에 저장
3. 초기 고슴도치 시작 좌표 큐에 저장 (물부터 진행해야 하기 때문. 고슴도치는 물이 다음 회차에 이동할 장소도 갈 수 없다.)
4. BFS 진행 (물(123)->고슴도치(456)) 고슴도치가 이동할 수 있는 경우가 없을 때 여부 판단.
4.1 물 좌표를 큐에서 하나씩 꺼내며 상하좌우의 물 이동 좌표 파악. boolean[][] 변경
4.2 예상 좌표를 새로운 물 좌표 큐에 저장
4.3 기존 물 좌표 큐가 비게 될 때, 새로운 물 좌표 큐를 기존 물 좌표 큐로 복사.
4.4 고슴도치 좌표 큐에서 하나씩 꺼내며 상하좌우로 고슴도치 이동 가능 여부 파악
4.5 도착 지점으로 이동 가능한 경우 현재 시간+1 반환
4.6 이동 가능한 경우 boolean[][] 변경 후 이동 좌표를 새로운 고슴도치 좌표 큐에 넣음.
4.7 시간 1초 증가 후 반복
5. 최종 결과값 출력
풀이시간 : 1시간 58분 16초
> [39일차] 김선후_BOJ_코테뿌셔_32

- day41/BOJ_2234_성곽/BOJ_2234_성곽_김선후.java
성곽
* 메모리 146416KB 시간 372ms
* 문제에서 서 북 남 동 순으로 벽이 존재할 시 1 2 4 8 을 더한 값을 의미한다.(비트마스킹 유추)
* bfs를 통하여 bfs가 끝마칠때마다 방의 개수를 구분할 수 있다.
* 벽을 허물기 전과 허문 후의 두단계로 나누어서 최대 넓이 값을 비교한다.
* bfs 매 실행시마다 해당 방의 넓이를 최대 방 넓이와 비교한다.
Solution 1.
1. bfs 탐색을 위한 map과 방문여부 배열의 선언 및 초기값 입력
2. 벽을 허물기 전 방의 개수와 최대 방 넓이를 구한다.
2.1. 해당 맵 좌표를 방문하지 않았다면 bfs 실행
2.2. 가고자 하는 방향과 바라보고 있는 벽의 방향(서,북,동,남 순)으로 bfs 탐색을 진행한다.
2.3. 해당 방향의 탐색이 끝날 시 진행방향과 벽의방향을 바꾼다.
2.4. bfs 탐색 사이클이 끝나면 해당 방의 넓이를 반환한다.
3. 벽을 허문 후 최대 방 넓이를 구한다.
3.1. (서,북,동,남 순)으로 해당 좌표와 벽의 방향의 & 연산시 벽이 있다면 벽을 제거후 bfs 진행
3.2. bfs 종료시 해당 좌표의 벽을 복구.
풀이시간 2시간 1분 42초
> [41일차] 김선후_BOJ_코테뿌셔_34

- day42/BOJ_12100_2048(Easy)/BOJ_12100_2048(Easy)_김선후.java
2048(easy)
* 메모리 26972KB 시간 260ms
* 한번에 한 방향으로만 이동이 가능, 이동 시 모든 블록이 같이 움직인다.
* 이동 과정에서 같은 값을 지닌 블록이 있으면 값을 합친다.
* 한번의 이동 과정에서 한번만 합쳐진다.
* 20*20*4*5 = 8000 O(N^2*D*MAXDEPTH) 완탐 사용 가능
Solution 1.
1. 문제 풀이에 사용될 맵의 초기상태 입력
2. 최대 5번의 깊이(최대이동수)를 지닌 재귀함수 실행
2.1 사방탐색을 통해 동일한 깊이에서 각각의 경우에서 이동된 맵을 다음 깊이의 재귀함수로 호출
2.2  이동방향이 위와 왼쪽은 좌측상단부터 탐색 시작, 이동방향이 아래와 오른쪽은 우측하단부터 탐색 시작
2.3  블록이 이동할 좌표값이 공백이면 경계를 벗어날때까지 계속 이동
2.4  블록이 이동할 좌표가 같은 값을 지닌 블록이면 합체여부에 따라 합체종료 혹은 바로종료
2.5  블록이 이동할 좌표가 다른 값을 지닌 블록이면 바로 종료
3. 최대깊이까지 재귀함수가 도달하면 현재 지니고 있는 맵의 최대값을 탐색 후 최대값 비교 갱신
4. 정답값 출력
풀이시간 1시간 27분 12초
> [42일차] 김선후_BOJ_코테뿌셔_35
